//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Writersword.Src.Modules.Characters.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CharactersStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CharactersStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Writersword.Src.Modules.Characters.Resources.CharactersStrings", typeof(CharactersStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a template....
        /// </summary>
        public static string Anketa_SelectPrompt {
            get {
                return ResourceManager.GetString("Anketa_SelectPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My Avatars.
        /// </summary>
        public static string AvatarPack_library {
            get {
                return ResourceManager.GetString("AvatarPack_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на People (minimalism).
        /// </summary>
        public static string AvatarPack_people_minimalism {
            get {
                return ResourceManager.GetString("AvatarPack_people_minimalism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string AvatarPicker_Cancel {
            get {
                return ResourceManager.GetString("AvatarPicker_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In project.
        /// </summary>
        public static string AvatarPicker_InProject {
            get {
                return ResourceManager.GetString("AvatarPicker_InProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manage packs.
        /// </summary>
        public static string AvatarPicker_ManagePacks {
            get {
                return ResourceManager.GetString("AvatarPicker_ManagePacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saved to library..
        /// </summary>
        public static string AvatarPicker_SavedToLibrary {
            get {
                return ResourceManager.GetString("AvatarPicker_SavedToLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to save.
        /// </summary>
        public static string AvatarPicker_SaveFailed {
            get {
                return ResourceManager.GetString("AvatarPicker_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saving….
        /// </summary>
        public static string AvatarPicker_Saving {
            get {
                return ResourceManager.GetString("AvatarPicker_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search avatars....
        /// </summary>
        public static string AvatarPicker_SearchPlaceholder {
            get {
                return ResourceManager.GetString("AvatarPicker_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose Avatar.
        /// </summary>
        public static string AvatarPicker_Title {
            get {
                return ResourceManager.GetString("AvatarPicker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Avatar.
        /// </summary>
        public static string AvatarPickerFlyout_Title {
            get {
                return ResourceManager.GetString("AvatarPickerFlyout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upload photo....
        /// </summary>
        public static string AvatarPickerFlyout_Upload {
            get {
                return ResourceManager.GetString("AvatarPickerFlyout_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add context.
        /// </summary>
        public static string Button_AddContext {
            get {
                return ResourceManager.GetString("Button_AddContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add event.
        /// </summary>
        public static string Button_AddEvent {
            get {
                return ResourceManager.GetString("Button_AddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add note.
        /// </summary>
        public static string Button_AddNote {
            get {
                return ResourceManager.GetString("Button_AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add parameter.
        /// </summary>
        public static string Button_AddParameter {
            get {
                return ResourceManager.GetString("Button_AddParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add relationship.
        /// </summary>
        public static string Button_AddRelationship {
            get {
                return ResourceManager.GetString("Button_AddRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add status.
        /// </summary>
        public static string Button_AddStatus {
            get {
                return ResourceManager.GetString("Button_AddStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply template.
        /// </summary>
        public static string Button_ApplyAnketa {
            get {
                return ResourceManager.GetString("Button_ApplyAnketa", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Labels.
        /// </summary>
        public static string Field_Labels {
            get {
                return ResourceManager.GetString("Field_Labels", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Add label.
        /// </summary>
        public static string Button_AddLabel {
            get {
                return ResourceManager.GetString("Button_AddLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Dead.
        /// </summary>
        public static string Label_Dead {
            get {
                return ResourceManager.GetString("Label_Dead", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на New label... (Enter).
        /// </summary>
        public static string Label_AddPlaceholder {
            get {
                return ResourceManager.GetString("Label_AddPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Add tag... (Enter).
        /// </summary>
        public static string Tag_AddPlaceholder {
            get {
                return ResourceManager.GetString("Tag_AddPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear filters.
        /// </summary>
        public static string Button_ClearFilters {
            get {
                return ResourceManager.GetString("Button_ClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New character.
        /// </summary>
        public static string Button_CreateCharacter {
            get {
                return ResourceManager.GetString("Button_CreateCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create group / people.
        /// </summary>
        public static string Button_CreateCollective {
            get {
                return ResourceManager.GetString("Button_CreateCollective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group.
        /// </summary>
        public static string Button_CreateCollectiveShort {
            get {
                return ResourceManager.GetString("Button_CreateCollectiveShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create randomized character.
        /// </summary>
        public static string Button_CreateRandomized {
            get {
                return ResourceManager.GetString("Button_CreateRandomized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete avatar.
        /// </summary>
        public static string Button_DeleteAvatar {
            get {
                return ResourceManager.GetString("Button_DeleteAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Duplicate.
        /// </summary>
        public static string Button_Duplicate {
            get {
                return ResourceManager.GetString("Button_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upload avatar.
        /// </summary>
        public static string Button_UploadAvatar {
            get {
                return ResourceManager.GetString("Button_UploadAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unnamed.
        /// </summary>
        public static string Character_DefaultName {
            get {
                return ResourceManager.GetString("Character_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string Character_EditTooltip {
            get {
                return ResourceManager.GetString("Character_EditTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unnamed.
        /// </summary>
        public static string Character_NamePlaceholder {
            get {
                return ResourceManager.GetString("Character_NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manage characters, relationships and templates.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на » will be deleted. All characters in it will become unassigned..
        /// </summary>
        public static string Dialog_DeleteFolder_After {
            get {
                return ResourceManager.GetString("Dialog_DeleteFolder_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder «.
        /// </summary>
        public static string Dialog_DeleteFolder_Before {
            get {
                return ResourceManager.GetString("Dialog_DeleteFolder_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete folder?.
        /// </summary>
        public static string Dialog_DeleteFolder_Title {
            get {
                return ResourceManager.GetString("Dialog_DeleteFolder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Characters.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color.
        /// </summary>
        public static string Field_Color {
            get {
                return ResourceManager.GetString("Field_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom label.
        /// </summary>
        public static string Field_CustomImportanceLabel {
            get {
                return ResourceManager.GetString("Field_CustomImportanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string Field_EventDescription {
            get {
                return ResourceManager.GetString("Field_EventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date / time.
        /// </summary>
        public static string Field_EventTimestamp {
            get {
                return ResourceManager.GetString("Field_EventTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        public static string Field_EventTitle {
            get {
                return ResourceManager.GetString("Field_EventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Icon.
        /// </summary>
        public static string Field_FallbackIcon {
            get {
                return ResourceManager.GetString("Field_FallbackIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Importance.
        /// </summary>
        public static string Field_ImportanceLevel {
            get {
                return ResourceManager.GetString("Field_ImportanceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Field_Name {
            get {
                return ResourceManager.GetString("Field_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last appearance.
        /// </summary>
        public static string Field_NarrativeEndPoint {
            get {
                return ResourceManager.GetString("Field_NarrativeEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First appearance.
        /// </summary>
        public static string Field_NarrativeStartPoint {
            get {
                return ResourceManager.GetString("Field_NarrativeStartPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Context.
        /// </summary>
        public static string Field_RelationshipContext {
            get {
                return ResourceManager.GetString("Field_RelationshipContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Emotion.
        /// </summary>
        public static string Field_RelationshipEmotion {
            get {
                return ResourceManager.GetString("Field_RelationshipEmotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Note.
        /// </summary>
        public static string Field_RelationshipNote {
            get {
                return ResourceManager.GetString("Field_RelationshipNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Strength.
        /// </summary>
        public static string Field_RelationshipStrength {
            get {
                return ResourceManager.GetString("Field_RelationshipStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        public static string Field_RelationshipType {
            get {
                return ResourceManager.GetString("Field_RelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Short description.
        /// </summary>
        public static string Field_ShortDescription {
            get {
                return ResourceManager.GetString("Field_ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Statuses.
        /// </summary>
        public static string Field_Statuses {
            get {
                return ResourceManager.GetString("Field_Statuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tags.
        /// </summary>
        public static string Field_Tags {
            get {
                return ResourceManager.GetString("Field_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All.
        /// </summary>
        public static string Filter_All {
            get {
                return ResourceManager.GetString("Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на comment....
        /// </summary>
        public static string Folder_CommentPlaceholder {
            get {
                return ResourceManager.GetString("Folder_CommentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add comment.
        /// </summary>
        public static string Folder_CommentTooltip {
            get {
                return ResourceManager.GetString("Folder_CommentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на + Folder.
        /// </summary>
        public static string Folder_CreateButton {
            get {
                return ResourceManager.GetString("Folder_CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create folder.
        /// </summary>
        public static string Folder_CreateTooltip {
            get {
                return ResourceManager.GetString("Folder_CreateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main Characters.
        /// </summary>
        public static string Folder_DefaultMain {
            get {
                return ResourceManager.GetString("Folder_DefaultMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Secondary Characters.
        /// </summary>
        public static string Folder_DefaultSecondary {
            get {
                return ResourceManager.GetString("Folder_DefaultSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder.
        /// </summary>
        public static string Folder_FallbackName {
            get {
                return ResourceManager.GetString("Folder_FallbackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Folder.
        /// </summary>
        public static string Folder_NewName {
            get {
                return ResourceManager.GetString("Folder_NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ungrouped.
        /// </summary>
        public static string Folder_Ungrouped {
            get {
                return ResourceManager.GetString("Folder_Ungrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear focus.
        /// </summary>
        public static string Graph_ClearFocus {
            get {
                return ResourceManager.GetString("Graph_ClearFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Right-click a node to focus.
        /// </summary>
        public static string Graph_FocusHint {
            get {
                return ResourceManager.GetString("Graph_FocusHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset view.
        /// </summary>
        public static string Graph_ResetView {
            get {
                return ResourceManager.GetString("Graph_ResetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Context.
        /// </summary>
        public static string HotKey_AddContext {
            get {
                return ResourceManager.GetString("HotKey_AddContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Note.
        /// </summary>
        public static string HotKey_AddNote {
            get {
                return ResourceManager.GetString("HotKey_AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Boolean Parameter.
        /// </summary>
        public static string HotKey_AddParameterBoolean {
            get {
                return ResourceManager.GetString("HotKey_AddParameterBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Numeric Parameter.
        /// </summary>
        public static string HotKey_AddParameterNumeric {
            get {
                return ResourceManager.GetString("HotKey_AddParameterNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add State List Parameter.
        /// </summary>
        public static string HotKey_AddParameterStateList {
            get {
                return ResourceManager.GetString("HotKey_AddParameterStateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Text Parameter.
        /// </summary>
        public static string HotKey_AddParameterText {
            get {
                return ResourceManager.GetString("HotKey_AddParameterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Relationship.
        /// </summary>
        public static string HotKey_AddRelationship {
            get {
                return ResourceManager.GetString("HotKey_AddRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Status.
        /// </summary>
        public static string HotKey_AddStatus {
            get {
                return ResourceManager.GetString("HotKey_AddStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Timeline Event.
        /// </summary>
        public static string HotKey_AddTimelineEvent {
            get {
                return ResourceManager.GetString("HotKey_AddTimelineEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear Filters.
        /// </summary>
        public static string HotKey_ClearFilters {
            get {
                return ResourceManager.GetString("HotKey_ClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close Card.
        /// </summary>
        public static string HotKey_CloseCard {
            get {
                return ResourceManager.GetString("HotKey_CloseCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Character.
        /// </summary>
        public static string HotKey_CreateCharacter {
            get {
                return ResourceManager.GetString("HotKey_CreateCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Group / People.
        /// </summary>
        public static string HotKey_CreateCollective {
            get {
                return ResourceManager.GetString("HotKey_CreateCollective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Randomized Character.
        /// </summary>
        public static string HotKey_CreateRandomized {
            get {
                return ResourceManager.GetString("HotKey_CreateRandomized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete Avatar.
        /// </summary>
        public static string HotKey_DeleteAvatar {
            get {
                return ResourceManager.GetString("HotKey_DeleteAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete Character.
        /// </summary>
        public static string HotKey_DeleteCharacter {
            get {
                return ResourceManager.GetString("HotKey_DeleteCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Duplicate Character.
        /// </summary>
        public static string HotKey_DuplicateCharacter {
            get {
                return ResourceManager.GetString("HotKey_DuplicateCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Focus Search.
        /// </summary>
        public static string HotKey_FocusSearch {
            get {
                return ResourceManager.GetString("HotKey_FocusSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Graph: Clear Focus.
        /// </summary>
        public static string HotKey_GraphClearFocus {
            get {
                return ResourceManager.GetString("HotKey_GraphClearFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Graph: Reset View.
        /// </summary>
        public static string HotKey_GraphResetView {
            get {
                return ResourceManager.GetString("HotKey_GraphResetView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Characters tab.
        /// </summary>
        public static string HotKey_OpenCharacters {
            get {
                return ResourceManager.GetString("HotKey_OpenCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Relationships tab.
        /// </summary>
        public static string HotKey_OpenRelationships {
            get {
                return ResourceManager.GetString("HotKey_OpenRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Templates tab.
        /// </summary>
        public static string HotKey_OpenTemplates {
            get {
                return ResourceManager.GetString("HotKey_OpenTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Randomize Parameters.
        /// </summary>
        public static string HotKey_RandomizeParameters {
            get {
                return ResourceManager.GetString("HotKey_RandomizeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save Card.
        /// </summary>
        public static string HotKey_SaveCard {
            get {
                return ResourceManager.GetString("HotKey_SaveCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to Basics tab.
        /// </summary>
        public static string HotKey_TabBasics {
            get {
                return ResourceManager.GetString("HotKey_TabBasics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to Contexts tab.
        /// </summary>
        public static string HotKey_TabContexts {
            get {
                return ResourceManager.GetString("HotKey_TabContexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to History tab.
        /// </summary>
        public static string HotKey_TabHistory {
            get {
                return ResourceManager.GetString("HotKey_TabHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next Tab.
        /// </summary>
        public static string HotKey_TabNext {
            get {
                return ResourceManager.GetString("HotKey_TabNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to Notes tab.
        /// </summary>
        public static string HotKey_TabNotes {
            get {
                return ResourceManager.GetString("HotKey_TabNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to Parameters tab.
        /// </summary>
        public static string HotKey_TabParameters {
            get {
                return ResourceManager.GetString("HotKey_TabParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to Timeline tab.
        /// </summary>
        public static string HotKey_TabPersonalTimeline {
            get {
                return ResourceManager.GetString("HotKey_TabPersonalTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous Tab.
        /// </summary>
        public static string HotKey_TabPrev {
            get {
                return ResourceManager.GetString("HotKey_TabPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to Relationships tab.
        /// </summary>
        public static string HotKey_TabRelationshipsCard {
            get {
                return ResourceManager.GetString("HotKey_TabRelationshipsCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upload Avatar.
        /// </summary>
        public static string HotKey_UploadAvatar {
            get {
                return ResourceManager.GetString("HotKey_UploadAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switch to Grid View.
        /// </summary>
        public static string HotKey_ViewGrid {
            get {
                return ResourceManager.GetString("HotKey_ViewGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switch to List View.
        /// </summary>
        public static string HotKey_ViewList {
            get {
                return ResourceManager.GetString("HotKey_ViewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter narrative point....
        /// </summary>
        public static string Placeholder_NarrativePoint {
            get {
                return ResourceManager.GetString("Placeholder_NarrativePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No characters yet. Create the first one..
        /// </summary>
        public static string Placeholder_NoCharacters {
            get {
                return ResourceManager.GetString("Placeholder_NoCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No events yet..
        /// </summary>
        public static string Placeholder_NoEvents {
            get {
                return ResourceManager.GetString("Placeholder_NoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No project events linked..
        /// </summary>
        public static string Placeholder_NoHistory {
            get {
                return ResourceManager.GetString("Placeholder_NoHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No notes yet..
        /// </summary>
        public static string Placeholder_NoNotes {
            get {
                return ResourceManager.GetString("Placeholder_NoNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No parameters yet. Add one or apply a template..
        /// </summary>
        public static string Placeholder_NoParameters {
            get {
                return ResourceManager.GetString("Placeholder_NoParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No relationships yet..
        /// </summary>
        public static string Placeholder_NoRelationships {
            get {
                return ResourceManager.GetString("Placeholder_NoRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a character to view details.
        /// </summary>
        public static string Placeholder_SelectCharacter {
            get {
                return ResourceManager.GetString("Placeholder_SelectCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search characters....
        /// </summary>
        public static string Search_Placeholder {
            get {
                return ResourceManager.GetString("Search_Placeholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Avatars only / full list.
        /// </summary>
        public static string EditorSidebar_ToggleCompact {
            get {
                return ResourceManager.GetString("EditorSidebar_ToggleCompact", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide list.
        /// </summary>
        public static string EditorSidebar_Hide {
            get {
                return ResourceManager.GetString("EditorSidebar_Hide", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Show list.
        /// </summary>
        public static string EditorSidebar_Show {
            get {
                return ResourceManager.GetString("EditorSidebar_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Basics.
        /// </summary>
        public static string Tab_Basics {
            get {
                return ResourceManager.GetString("Tab_Basics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Characters.
        /// </summary>
        public static string Tab_Characters {
            get {
                return ResourceManager.GetString("Tab_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contexts.
        /// </summary>
        public static string Tab_Contexts {
            get {
                return ResourceManager.GetString("Tab_Contexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Character Editor.
        /// </summary>
        public static string Tab_Edit {
            get {
                return ResourceManager.GetString("Tab_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на History.
        /// </summary>
        public static string Tab_History {
            get {
                return ResourceManager.GetString("Tab_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notes.
        /// </summary>
        public static string Tab_Notes {
            get {
                return ResourceManager.GetString("Tab_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters.
        /// </summary>
        public static string Tab_Parameters {
            get {
                return ResourceManager.GetString("Tab_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timeline.
        /// </summary>
        public static string Tab_PersonalTimeline {
            get {
                return ResourceManager.GetString("Tab_PersonalTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Relationships.
        /// </summary>
        public static string Tab_Relationships {
            get {
                return ResourceManager.GetString("Tab_Relationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Templates.
        /// </summary>
        public static string Tab_Templates {
            get {
                return ResourceManager.GetString("Tab_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BUILT-IN TEMPLATES.
        /// </summary>
        public static string Templates_BuiltInHeader {
            get {
                return ResourceManager.GetString("Templates_BuiltInHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy.
        /// </summary>
        public static string Templates_Copy {
            get {
                return ResourceManager.GetString("Templates_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на + Create template.
        /// </summary>
        public static string Templates_CreateCustom {
            get {
                return ResourceManager.GetString("Templates_CreateCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MY TEMPLATES.
        /// </summary>
        public static string Templates_CustomHeader {
            get {
                return ResourceManager.GetString("Templates_CustomHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Templates_Delete {
            get {
                return ResourceManager.GetString("Templates_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на parameters.
        /// </summary>
        public static string Templates_FieldCountSuffix {
            get {
                return ResourceManager.GetString("Templates_FieldCountSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WHAT DO YOU NEED?.
        /// </summary>
        public static string Templates_FiltersHeader {
            get {
                return ResourceManager.GetString("Templates_FiltersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No custom templates yet..
        /// </summary>
        public static string Templates_NoCustom {
            get {
                return ResourceManager.GetString("Templates_NoCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reconfigure....
        /// </summary>
        public static string Templates_RestartOnboarding {
            get {
                return ResourceManager.GetString("Templates_RestartOnboarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Grid.
        /// </summary>
        public static string ViewMode_Grid {
            get {
                return ResourceManager.GetString("ViewMode_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List.
        /// </summary>
        public static string ViewMode_List {
            get {
                return ResourceManager.GetString("ViewMode_List", resourceCulture);
            }
        }

        public static string FilePicker_ImagesFilter {
            get {
                return ResourceManager.GetString("FilePicker_ImagesFilter", resourceCulture);
            }
        }

        public static string FilePicker_SelectImageTitle {
            get {
                return ResourceManager.GetString("FilePicker_SelectImageTitle", resourceCulture);
            }
        }

        public static string AvatarPackManager_Title {
            get {
                return ResourceManager.GetString("AvatarPackManager_Title", resourceCulture);
            }
        }

        public static string AvatarPackManager_BuiltInBadge {
            get {
                return ResourceManager.GetString("AvatarPackManager_BuiltInBadge", resourceCulture);
            }
        }

        public static string AvatarPackManager_NewPackPlaceholder {
            get {
                return ResourceManager.GetString("AvatarPackManager_NewPackPlaceholder", resourceCulture);
            }
        }

        public static string AvatarPackManager_CreatePack {
            get {
                return ResourceManager.GetString("AvatarPackManager_CreatePack", resourceCulture);
            }
        }

        public static string AvatarPackManager_ImportZip {
            get {
                return ResourceManager.GetString("AvatarPackManager_ImportZip", resourceCulture);
            }
        }

        public static string AvatarPackManager_SelectPackHint {
            get {
                return ResourceManager.GetString("AvatarPackManager_SelectPackHint", resourceCulture);
            }
        }

        public static string AvatarPackManager_ExportZip {
            get {
                return ResourceManager.GetString("AvatarPackManager_ExportZip", resourceCulture);
            }
        }

        public static string AvatarPackManager_DeletePack {
            get {
                return ResourceManager.GetString("AvatarPackManager_DeletePack", resourceCulture);
            }
        }

        public static string AvatarPackManager_BuiltInHint {
            get {
                return ResourceManager.GetString("AvatarPackManager_BuiltInHint", resourceCulture);
            }
        }

        public static string Avatar_PickTooltip {
            get {
                return ResourceManager.GetString("Avatar_PickTooltip", resourceCulture);
            }
        }

        public static string ViewMode_Tooltip {
            get {
                return ResourceManager.GetString("ViewMode_Tooltip", resourceCulture);
            }
        }

        public static string ViewMode_Small {
            get {
                return ResourceManager.GetString("ViewMode_Small", resourceCulture);
            }
        }

        public static string ViewMode_Medium {
            get {
                return ResourceManager.GetString("ViewMode_Medium", resourceCulture);
            }
        }

        public static string ViewMode_Large {
            get {
                return ResourceManager.GetString("ViewMode_Large", resourceCulture);
            }
        }

        public static string ViewMode_Huge {
            get {
                return ResourceManager.GetString("ViewMode_Huge", resourceCulture);
            }
        }

        public static string Folder_DeleteTooltip {
            get {
                return ResourceManager.GetString("Folder_DeleteTooltip", resourceCulture);
            }
        }

        public static string ColorPicker_Tooltip {
            get {
                return ResourceManager.GetString("ColorPicker_Tooltip", resourceCulture);
            }
        }

        public static string Character_DeleteTooltip {
            get {
                return ResourceManager.GetString("Character_DeleteTooltip", resourceCulture);
            }
        }

        public static string Character_RenameTooltip {
            get {
                return ResourceManager.GetString("Character_RenameTooltip", resourceCulture);
            }
        }

        public static string Loading_Characters {
            get {
                return ResourceManager.GetString("Loading_Characters", resourceCulture);
            }
        }

        public static string Relationship_BidirectionalTooltip {
            get {
                return ResourceManager.GetString("Relationship_BidirectionalTooltip", resourceCulture);
            }
        }

        public static string Timeline_KeyEventTooltip {
            get {
                return ResourceManager.GetString("Timeline_KeyEventTooltip", resourceCulture);
            }
        }

        public static string Param_AddNumeric {
            get {
                return ResourceManager.GetString("Param_AddNumeric", resourceCulture);
            }
        }

        public static string Param_HintScale {
            get {
                return ResourceManager.GetString("Param_HintScale", resourceCulture);
            }
        }

        public static string Param_HintText {
            get {
                return ResourceManager.GetString("Param_HintText", resourceCulture);
            }
        }

        public static string Param_HintChoice {
            get {
                return ResourceManager.GetString("Param_HintChoice", resourceCulture);
            }
        }

        public static string Param_HintYesNo {
            get {
                return ResourceManager.GetString("Param_HintYesNo", resourceCulture);
            }
        }

        public static string Param_NotApplicable {
            get {
                return ResourceManager.GetString("Param_NotApplicable", resourceCulture);
            }
        }

        public static string Param_NotApplicableHint {
            get {
                return ResourceManager.GetString("Param_NotApplicableHint", resourceCulture);
            }
        }

        public static string Param_MoveUpTooltip {
            get {
                return ResourceManager.GetString("Param_MoveUpTooltip", resourceCulture);
            }
        }

        public static string Block_General {
            get {
                return ResourceManager.GetString("Block_General", resourceCulture);
            }
        }

        public static string Block_Appearance {
            get {
                return ResourceManager.GetString("Block_Appearance", resourceCulture);
            }
        }

        public static string Onboarding_Back {
            get {
                return ResourceManager.GetString("Onboarding_Back", resourceCulture);
            }
        }

        public static string Compare_Title {
            get {
                return ResourceManager.GetString("Compare_Title", resourceCulture);
            }
        }

        public static string Compare_Summary {
            get {
                return ResourceManager.GetString("Compare_Summary", resourceCulture);
            }
        }

        public static string Compare_Empty {
            get {
                return ResourceManager.GetString("Compare_Empty", resourceCulture);
            }
        }

        public static string Compare_Button {
            get {
                return ResourceManager.GetString("Compare_Button", resourceCulture);
            }
        }

        public static string Compare_Hint {
            get {
                return ResourceManager.GetString("Compare_Hint", resourceCulture);
            }
        }

        public static string Field_GroupAddresses {
            get {
                return ResourceManager.GetString("Field_GroupAddresses", resourceCulture);
            }
        }

        public static string Hint_GroupAddresses {
            get {
                return ResourceManager.GetString("Hint_GroupAddresses", resourceCulture);
            }
        }

        public static string GroupAddress_Placeholder {
            get {
                return ResourceManager.GetString("GroupAddress_Placeholder", resourceCulture);
            }
        }

        public static string Field_DefaultAddress {
            get {
                return ResourceManager.GetString("Field_DefaultAddress", resourceCulture);
            }
        }

        public static string Hint_DefaultAddress {
            get {
                return ResourceManager.GetString("Hint_DefaultAddress", resourceCulture);
            }
        }

        public static string Placeholder_DefaultAddress {
            get {
                return ResourceManager.GetString("Placeholder_DefaultAddress", resourceCulture);
            }
        }

        public static string Block_Who {
            get {
                return ResourceManager.GetString("Block_Who", resourceCulture);
            }
        }

        public static string Block_Names {
            get {
                return ResourceManager.GetString("Block_Names", resourceCulture);
            }
        }

        public static string Block_Classification {
            get {
                return ResourceManager.GetString("Block_Classification", resourceCulture);
            }
        }

        public static string Block_Gallery {
            get {
                return ResourceManager.GetString("Block_Gallery", resourceCulture);
            }
        }

        public static string Gallery_Hint {
            get {
                return ResourceManager.GetString("Gallery_Hint", resourceCulture);
            }
        }

        public static string Gallery_Add {
            get {
                return ResourceManager.GetString("Gallery_Add", resourceCulture);
            }
        }

        public static string Gallery_Empty {
            get {
                return ResourceManager.GetString("Gallery_Empty", resourceCulture);
            }
        }

        public static string Gallery_Remove {
            get {
                return ResourceManager.GetString("Gallery_Remove", resourceCulture);
            }
        }

        public static string Gallery_UseAsAvatar {
            get {
                return ResourceManager.GetString("Gallery_UseAsAvatar", resourceCulture);
            }
        }

        public static string Block_Group {
            get {
                return ResourceManager.GetString("Block_Group", resourceCulture);
            }
        }

        public static string Group_Hint {
            get {
                return ResourceManager.GetString("Group_Hint", resourceCulture);
            }
        }

        public static string Group_Population {
            get {
                return ResourceManager.GetString("Group_Population", resourceCulture);
            }
        }

        public static string Group_PopulationPlaceholder {
            get {
                return ResourceManager.GetString("Group_PopulationPlaceholder", resourceCulture);
            }
        }

        public static string Sets_EmptyHint {
            get {
                return ResourceManager.GetString("Sets_EmptyHint", resourceCulture);
            }
        }

        public static string Sets_FieldCount {
            get {
                return ResourceManager.GetString("Sets_FieldCount", resourceCulture);
            }
        }

        public static string Block_DataSets {
            get {
                return ResourceManager.GetString("Block_DataSets", resourceCulture);
            }
        }

        public static string Block_DataSetsHint {
            get {
                return ResourceManager.GetString("Block_DataSetsHint", resourceCulture);
            }
        }

        public static string Templates_Export {
            get {
                return ResourceManager.GetString("Templates_Export", resourceCulture);
            }
        }

        public static string Templates_Import {
            get {
                return ResourceManager.GetString("Templates_Import", resourceCulture);
            }
        }

        public static string Templates_Edit {
            get {
                return ResourceManager.GetString("Templates_Edit", resourceCulture);
            }
        }

        public static string AnketaEditor_Title {
            get {
                return ResourceManager.GetString("AnketaEditor_Title", resourceCulture);
            }
        }

        public static string AnketaEditor_Name {
            get {
                return ResourceManager.GetString("AnketaEditor_Name", resourceCulture);
            }
        }

        public static string AnketaEditor_Description {
            get {
                return ResourceManager.GetString("AnketaEditor_Description", resourceCulture);
            }
        }

        public static string AnketaEditor_Empty {
            get {
                return ResourceManager.GetString("AnketaEditor_Empty", resourceCulture);
            }
        }

        public static string AnketaEditor_FieldName {
            get {
                return ResourceManager.GetString("AnketaEditor_FieldName", resourceCulture);
            }
        }

        public static string AnketaEditor_FieldHint {
            get {
                return ResourceManager.GetString("AnketaEditor_FieldHint", resourceCulture);
            }
        }

        public static string AnketaEditor_ScaleLabels {
            get {
                return ResourceManager.GetString("AnketaEditor_ScaleLabels", resourceCulture);
            }
        }

        public static string AnketaEditor_ScaleLabelsHint {
            get {
                return ResourceManager.GetString("AnketaEditor_ScaleLabelsHint", resourceCulture);
            }
        }

        public static string AnketaEditor_Choices {
            get {
                return ResourceManager.GetString("AnketaEditor_Choices", resourceCulture);
            }
        }

        public static string AnketaEditor_Comparable {
            get {
                return ResourceManager.GetString("AnketaEditor_Comparable", resourceCulture);
            }
        }

        public static string AnketaEditor_ComparableHint {
            get {
                return ResourceManager.GetString("AnketaEditor_ComparableHint", resourceCulture);
            }
        }

        public static string AnketaEditor_Save {
            get {
                return ResourceManager.GetString("AnketaEditor_Save", resourceCulture);
            }
        }

        public static string AnketaEditor_Cancel {
            get {
                return ResourceManager.GetString("AnketaEditor_Cancel", resourceCulture);
            }
        }

        public static string Hint_SetsMovedShort {
            get {
                return ResourceManager.GetString("Hint_SetsMovedShort", resourceCulture);
            }
        }

        public static string Hint_Sets {
            get {
                return ResourceManager.GetString("Hint_Sets", resourceCulture);
            }
        }

        public static string Anketa_Attached {
            get {
                return ResourceManager.GetString("Anketa_Attached", resourceCulture);
            }
        }

        public static string Anketa_DetachTip {
            get {
                return ResourceManager.GetString("Anketa_DetachTip", resourceCulture);
            }
        }

        public static string Anketa_DetachHint {
            get {
                return ResourceManager.GetString("Anketa_DetachHint", resourceCulture);
            }
        }

        public static string Relationship_FilterPositive {
            get {
                return ResourceManager.GetString("Relationship_FilterPositive", resourceCulture);
            }
        }

        public static string Relationship_FilterNegative {
            get {
                return ResourceManager.GetString("Relationship_FilterNegative", resourceCulture);
            }
        }

        public static string Relationship_FilterHint {
            get {
                return ResourceManager.GetString("Relationship_FilterHint", resourceCulture);
            }
        }

        public static string Hint_Labels {
            get {
                return ResourceManager.GetString("Hint_Labels", resourceCulture);
            }
        }

        public static string Hint_Tags {
            get {
                return ResourceManager.GetString("Hint_Tags", resourceCulture);
            }
        }

        public static string Hint_AlternateNames {
            get {
                return ResourceManager.GetString("Hint_AlternateNames", resourceCulture);
            }
        }

        public static string Hint_Note {
            get {
                return ResourceManager.GetString("Hint_Note", resourceCulture);
            }
        }

        public static string Param_ValueNotePlaceholder {
            get {
                return ResourceManager.GetString("Param_ValueNotePlaceholder", resourceCulture);
            }
        }

        public static string Field_AlternateNames {
            get {
                return ResourceManager.GetString("Field_AlternateNames", resourceCulture);
            }
        }

        public static string Name_AddPlaceholder {
            get {
                return ResourceManager.GetString("Name_AddPlaceholder", resourceCulture);
            }
        }

        public static string Name_MakePrimary {
            get {
                return ResourceManager.GetString("Name_MakePrimary", resourceCulture);
            }
        }

        public static string Field_Note {
            get {
                return ResourceManager.GetString("Field_Note", resourceCulture);
            }
        }

        public static string Placeholder_Note {
            get {
                return ResourceManager.GetString("Placeholder_Note", resourceCulture);
            }
        }

        public static string Button_AddSet {
            get {
                return ResourceManager.GetString("Button_AddSet", resourceCulture);
            }
        }

        public static string Relationship_DropHint {
            get {
                return ResourceManager.GetString("Relationship_DropHint", resourceCulture);
            }
        }

        public static string Relationship_CallsAs {
            get {
                return ResourceManager.GetString("Relationship_CallsAs", resourceCulture);
            }
        }

        public static string Relationship_CallsAsHint {
            get {
                return ResourceManager.GetString("Relationship_CallsAsHint", resourceCulture);
            }
        }

        public static string Relationship_CallsAsPlaceholder {
            get {
                return ResourceManager.GetString("Relationship_CallsAsPlaceholder", resourceCulture);
            }
        }

        public static string Relationship_Candidates {
            get {
                return ResourceManager.GetString("Relationship_Candidates", resourceCulture);
            }
        }

        public static string Relationship_FilterAll {
            get {
                return ResourceManager.GetString("Relationship_FilterAll", resourceCulture);
            }
        }

        public static string Relationship_SelectHint {
            get {
                return ResourceManager.GetString("Relationship_SelectHint", resourceCulture);
            }
        }

        public static string Param_AddText {
            get {
                return ResourceManager.GetString("Param_AddText", resourceCulture);
            }
        }

        public static string Param_AddStateList {
            get {
                return ResourceManager.GetString("Param_AddStateList", resourceCulture);
            }
        }

        public static string Param_AddBoolean {
            get {
                return ResourceManager.GetString("Param_AddBoolean", resourceCulture);
            }
        }

        public static string Param_DescriptionPlaceholder {
            get {
                return ResourceManager.GetString("Param_DescriptionPlaceholder", resourceCulture);
            }
        }

        public static string Param_MinPlaceholder {
            get {
                return ResourceManager.GetString("Param_MinPlaceholder", resourceCulture);
            }
        }

        public static string Param_MaxPlaceholder {
            get {
                return ResourceManager.GetString("Param_MaxPlaceholder", resourceCulture);
            }
        }

        public static string Note_TitlePlaceholder {
            get {
                return ResourceManager.GetString("Note_TitlePlaceholder", resourceCulture);
            }
        }

        public static string Note_BodyPlaceholder {
            get {
                return ResourceManager.GetString("Note_BodyPlaceholder", resourceCulture);
            }
        }

        public static string Context_NameLabel {
            get {
                return ResourceManager.GetString("Context_NameLabel", resourceCulture);
            }
        }

        public static string Context_WhenActiveLabel {
            get {
                return ResourceManager.GetString("Context_WhenActiveLabel", resourceCulture);
            }
        }

        public static string Context_ColorLabel {
            get {
                return ResourceManager.GetString("Context_ColorLabel", resourceCulture);
            }
        }

        public static string Context_NotesLabel {
            get {
                return ResourceManager.GetString("Context_NotesLabel", resourceCulture);
            }
        }

        public static string Context_EmptyHint {
            get {
                return ResourceManager.GetString("Context_EmptyHint", resourceCulture);
            }
        }

        public static string Onboarding_Title {
            get {
                return ResourceManager.GetString("Onboarding_Title", resourceCulture);
            }
        }

        public static string Onboarding_Subtitle {
            get {
                return ResourceManager.GetString("Onboarding_Subtitle", resourceCulture);
            }
        }

        public static string Onboarding_Skip {
            get {
                return ResourceManager.GetString("Onboarding_Skip", resourceCulture);
            }
        }

        public static string Onboarding_ApplyTemplates {
            get {
                return ResourceManager.GetString("Onboarding_ApplyTemplates", resourceCulture);
            }
        }

        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }

        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }

        public static string Template_Apply {
            get {
                return ResourceManager.GetString("Template_Apply", resourceCulture);
            }
        }

        public static string Template_Applied {
            get {
                return ResourceManager.GetString("Template_Applied", resourceCulture);
            }
        }

        public static string Toast_CharacterDeleted {
            get {
                return ResourceManager.GetString("Toast_CharacterDeleted", resourceCulture);
            }
        }
    }
}
