//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Writersword.Modules.Characters.Resources
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CharactersStrings
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CharactersStrings() { }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(
                        "Writersword.Src.Modules.Characters.Resources.CharactersStrings",
                        typeof(CharactersStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        // ── Метаданные модуля ────────────────────────────────────────────
        public static string DisplayName => ResourceManager.GetString("DisplayName", resourceCulture);
        public static string Description => ResourceManager.GetString("Description", resourceCulture);

        // ── Вкладки модуля ────────────────────────────────────────────────
        public static string Tab_Characters => ResourceManager.GetString("Tab_Characters", resourceCulture);
        public static string Tab_Edit => ResourceManager.GetString("Tab_Edit", resourceCulture);
        public static string Tab_Relationships => ResourceManager.GetString("Tab_Relationships", resourceCulture);
        public static string Tab_Templates => ResourceManager.GetString("Tab_Templates", resourceCulture);

        // ── Вкладки карточки ─────────────────────────────────────────────
        public static string Tab_Basics => ResourceManager.GetString("Tab_Basics", resourceCulture);
        public static string Tab_Parameters => ResourceManager.GetString("Tab_Parameters", resourceCulture);
        public static string Tab_Contexts => ResourceManager.GetString("Tab_Contexts", resourceCulture);
        public static string Tab_Notes => ResourceManager.GetString("Tab_Notes", resourceCulture);
        public static string Tab_PersonalTimeline => ResourceManager.GetString("Tab_PersonalTimeline", resourceCulture);
        public static string Tab_History => ResourceManager.GetString("Tab_History", resourceCulture);

        // ── Режимы отображения ───────────────────────────────────────────
        public static string ViewMode_List => ResourceManager.GetString("ViewMode_List", resourceCulture);
        public static string ViewMode_Grid => ResourceManager.GetString("ViewMode_Grid", resourceCulture);

        // ── Кнопки ───────────────────────────────────────────────────────
        public static string Button_CreateCharacter => ResourceManager.GetString("Button_CreateCharacter", resourceCulture);
        public static string Button_CreateRandomized => ResourceManager.GetString("Button_CreateRandomized", resourceCulture);
        public static string Button_CreateCollective => ResourceManager.GetString("Button_CreateCollective", resourceCulture);
        public static string Button_Save => ResourceManager.GetString("Button_Save", resourceCulture);
        public static string Button_Delete => ResourceManager.GetString("Button_Delete", resourceCulture);
        public static string Button_Duplicate => ResourceManager.GetString("Button_Duplicate", resourceCulture);
        public static string Button_UploadAvatar => ResourceManager.GetString("Button_UploadAvatar", resourceCulture);
        public static string Button_DeleteAvatar => ResourceManager.GetString("Button_DeleteAvatar", resourceCulture);
        public static string Button_AddStatus => ResourceManager.GetString("Button_AddStatus", resourceCulture);
        public static string Button_AddParameter => ResourceManager.GetString("Button_AddParameter", resourceCulture);
        public static string Button_AddContext => ResourceManager.GetString("Button_AddContext", resourceCulture);
        public static string Button_AddRelationship => ResourceManager.GetString("Button_AddRelationship", resourceCulture);
        public static string Button_AddNote => ResourceManager.GetString("Button_AddNote", resourceCulture);
        public static string Button_AddEvent => ResourceManager.GetString("Button_AddEvent", resourceCulture);
        public static string Button_ApplyAnketa => ResourceManager.GetString("Button_ApplyAnketa", resourceCulture);
        public static string Button_ClearFilters => ResourceManager.GetString("Button_ClearFilters", resourceCulture);

        // ── Поля карточки ────────────────────────────────────────────────
        public static string Field_Name => ResourceManager.GetString("Field_Name", resourceCulture);
        public static string Field_ShortDescription => ResourceManager.GetString("Field_ShortDescription", resourceCulture);
        public static string Field_Color => ResourceManager.GetString("Field_Color", resourceCulture);
        public static string Field_FallbackIcon => ResourceManager.GetString("Field_FallbackIcon", resourceCulture);
        public static string Field_ImportanceLevel => ResourceManager.GetString("Field_ImportanceLevel", resourceCulture);
        public static string Field_CustomImportanceLabel => ResourceManager.GetString("Field_CustomImportanceLabel", resourceCulture);
        public static string Field_NarrativeStartPoint => ResourceManager.GetString("Field_NarrativeStartPoint", resourceCulture);
        public static string Field_NarrativeEndPoint => ResourceManager.GetString("Field_NarrativeEndPoint", resourceCulture);
        public static string Field_Tags => ResourceManager.GetString("Field_Tags", resourceCulture);
        public static string Field_Statuses => ResourceManager.GetString("Field_Statuses", resourceCulture);
        public static string Field_RelationshipType => ResourceManager.GetString("Field_RelationshipType", resourceCulture);
        public static string Field_RelationshipStrength => ResourceManager.GetString("Field_RelationshipStrength", resourceCulture);
        public static string Field_RelationshipContext => ResourceManager.GetString("Field_RelationshipContext", resourceCulture);
        public static string Field_RelationshipEmotion => ResourceManager.GetString("Field_RelationshipEmotion", resourceCulture);
        public static string Field_RelationshipNote => ResourceManager.GetString("Field_RelationshipNote", resourceCulture);
        public static string Field_EventTitle => ResourceManager.GetString("Field_EventTitle", resourceCulture);
        public static string Field_EventTimestamp => ResourceManager.GetString("Field_EventTimestamp", resourceCulture);
        public static string Field_EventDescription => ResourceManager.GetString("Field_EventDescription", resourceCulture);

        // ── Плейсхолдеры ─────────────────────────────────────────────────
        public static string Search_Placeholder => ResourceManager.GetString("Search_Placeholder", resourceCulture);
        public static string Placeholder_SelectCharacter => ResourceManager.GetString("Placeholder_SelectCharacter", resourceCulture);
        public static string Placeholder_NarrativePoint => ResourceManager.GetString("Placeholder_NarrativePoint", resourceCulture);
        public static string Placeholder_NoParameters => ResourceManager.GetString("Placeholder_NoParameters", resourceCulture);
        public static string Placeholder_NoRelationships => ResourceManager.GetString("Placeholder_NoRelationships", resourceCulture);
        public static string Placeholder_NoNotes => ResourceManager.GetString("Placeholder_NoNotes", resourceCulture);
        public static string Placeholder_NoEvents => ResourceManager.GetString("Placeholder_NoEvents", resourceCulture);
        public static string Placeholder_NoHistory => ResourceManager.GetString("Placeholder_NoHistory", resourceCulture);
        public static string Placeholder_NoCharacters => ResourceManager.GetString("Placeholder_NoCharacters", resourceCulture);

        // ── Фильтры ───────────────────────────────────────────────────────
        public static string Filter_All => ResourceManager.GetString("Filter_All", resourceCulture);

        // ── Граф ─────────────────────────────────────────────────────────
        public static string Graph_ResetView => ResourceManager.GetString("Graph_ResetView", resourceCulture);
        public static string Graph_ClearFocus => ResourceManager.GetString("Graph_ClearFocus", resourceCulture);
        public static string Graph_FocusHint => ResourceManager.GetString("Graph_FocusHint", resourceCulture);

        // ── Анкеты ───────────────────────────────────────────────────────
        public static string Anketa_SelectPrompt => ResourceManager.GetString("Anketa_SelectPrompt", resourceCulture);

        // ── Горячие клавиши — Модуль ──────────────────────────────────────
        public static string HotKey_CreateCharacter => ResourceManager.GetString("HotKey_CreateCharacter", resourceCulture);
        public static string HotKey_CreateRandomized => ResourceManager.GetString("HotKey_CreateRandomized", resourceCulture);
        public static string HotKey_CreateCollective => ResourceManager.GetString("HotKey_CreateCollective", resourceCulture);
        public static string HotKey_OpenCharacters => ResourceManager.GetString("HotKey_OpenCharacters", resourceCulture);
        public static string HotKey_OpenRelationships => ResourceManager.GetString("HotKey_OpenRelationships", resourceCulture);
        public static string HotKey_OpenTemplates => ResourceManager.GetString("HotKey_OpenTemplates", resourceCulture);
        public static string HotKey_DeleteCharacter => ResourceManager.GetString("HotKey_DeleteCharacter", resourceCulture);
        public static string HotKey_DuplicateCharacter => ResourceManager.GetString("HotKey_DuplicateCharacter", resourceCulture);
        public static string HotKey_SaveCard => ResourceManager.GetString("HotKey_SaveCard", resourceCulture);
        public static string HotKey_CloseCard => ResourceManager.GetString("HotKey_CloseCard", resourceCulture);
        public static string HotKey_FocusSearch => ResourceManager.GetString("HotKey_FocusSearch", resourceCulture);
        public static string HotKey_ClearFilters => ResourceManager.GetString("HotKey_ClearFilters", resourceCulture);

        // ── Горячие клавиши — Режимы ──────────────────────────────────────
        public static string HotKey_ViewList => ResourceManager.GetString("HotKey_ViewList", resourceCulture);
        public static string HotKey_ViewGrid => ResourceManager.GetString("HotKey_ViewGrid", resourceCulture);

        // ── Горячие клавиши — Навигация по вкладкам ──────────────────────
        public static string HotKey_TabNext => ResourceManager.GetString("HotKey_TabNext", resourceCulture);
        public static string HotKey_TabPrev => ResourceManager.GetString("HotKey_TabPrev", resourceCulture);
        public static string HotKey_TabBasics => ResourceManager.GetString("HotKey_TabBasics", resourceCulture);
        public static string HotKey_TabParameters => ResourceManager.GetString("HotKey_TabParameters", resourceCulture);
        public static string HotKey_TabRelationshipsCard => ResourceManager.GetString("HotKey_TabRelationshipsCard", resourceCulture);
        public static string HotKey_TabContexts => ResourceManager.GetString("HotKey_TabContexts", resourceCulture);
        public static string HotKey_TabNotes => ResourceManager.GetString("HotKey_TabNotes", resourceCulture);
        public static string HotKey_TabPersonalTimeline => ResourceManager.GetString("HotKey_TabPersonalTimeline", resourceCulture);
        public static string HotKey_TabHistory => ResourceManager.GetString("HotKey_TabHistory", resourceCulture);

        // ── Горячие клавиши — Действия в карточке ────────────────────────
        public static string HotKey_AddParameterNumeric => ResourceManager.GetString("HotKey_AddParameterNumeric", resourceCulture);
        public static string HotKey_AddParameterText => ResourceManager.GetString("HotKey_AddParameterText", resourceCulture);
        public static string HotKey_AddParameterStateList => ResourceManager.GetString("HotKey_AddParameterStateList", resourceCulture);
        public static string HotKey_AddParameterBoolean => ResourceManager.GetString("HotKey_AddParameterBoolean", resourceCulture);
        public static string HotKey_AddContext => ResourceManager.GetString("HotKey_AddContext", resourceCulture);
        public static string HotKey_AddRelationship => ResourceManager.GetString("HotKey_AddRelationship", resourceCulture);
        public static string HotKey_AddNote => ResourceManager.GetString("HotKey_AddNote", resourceCulture);
        public static string HotKey_AddTimelineEvent => ResourceManager.GetString("HotKey_AddTimelineEvent", resourceCulture);
        public static string HotKey_AddStatus => ResourceManager.GetString("HotKey_AddStatus", resourceCulture);
        public static string HotKey_UploadAvatar => ResourceManager.GetString("HotKey_UploadAvatar", resourceCulture);
        public static string HotKey_DeleteAvatar => ResourceManager.GetString("HotKey_DeleteAvatar", resourceCulture);
        public static string HotKey_RandomizeParameters => ResourceManager.GetString("HotKey_RandomizeParameters", resourceCulture);

        // ── Горячие клавиши — Граф ───────────────────────────────────────
        public static string HotKey_GraphResetView => ResourceManager.GetString("HotKey_GraphResetView", resourceCulture);
        public static string HotKey_GraphClearFocus => ResourceManager.GetString("HotKey_GraphClearFocus", resourceCulture);
    }
}