//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Writersword.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Writersword.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unsaved version found (auto-save).
        /// </summary>
        public static string AutoSave_Banner_CacheFound {
            get {
                return ResourceManager.GetString("AutoSave_Banner_CacheFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Viewing: Auto-save.
        /// </summary>
        public static string AutoSave_Banner_ViewingCache {
            get {
                return ResourceManager.GetString("AutoSave_Banner_ViewingCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Viewing: Saved version.
        /// </summary>
        public static string AutoSave_Banner_ViewingSaved {
            get {
                return ResourceManager.GetString("AutoSave_Banner_ViewingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete Auto-save.
        /// </summary>
        public static string AutoSave_Button_DeleteAutoSave {
            get {
                return ResourceManager.GetString("AutoSave_Button_DeleteAutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Discard Changes.
        /// </summary>
        public static string AutoSave_Button_DiscardChanges {
            get {
                return ResourceManager.GetString("AutoSave_Button_DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Auto-save.
        /// </summary>
        public static string AutoSave_Button_OpenAutoSave {
            get {
                return ResourceManager.GetString("AutoSave_Button_OpenAutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save and Continue.
        /// </summary>
        public static string AutoSave_Button_SaveAndContinue {
            get {
                return ResourceManager.GetString("AutoSave_Button_SaveAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switch to Auto-save.
        /// </summary>
        public static string AutoSave_Button_SwitchToCache {
            get {
                return ResourceManager.GetString("AutoSave_Button_SwitchToCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switch to Saved version.
        /// </summary>
        public static string AutoSave_Button_SwitchToSaved {
            get {
                return ResourceManager.GetString("AutoSave_Button_SwitchToSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto-save:.
        /// </summary>
        public static string AutoSave_Time_AutoSave {
            get {
                return ResourceManager.GetString("AutoSave_Time_AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saved:.
        /// </summary>
        public static string AutoSave_Time_Saved {
            get {
                return ResourceManager.GetString("AutoSave_Time_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        public static string Common_Apply {
            get {
                return ResourceManager.GetString("Common_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete auto-save?.
        /// </summary>
        public static string Dialog_ConfirmDeleteCache_Message_Line1 {
            get {
                return ResourceManager.GetString("Dialog_ConfirmDeleteCache_Message_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changes will be lost..
        /// </summary>
        public static string Dialog_ConfirmDeleteCache_Message_Line2 {
            get {
                return ResourceManager.GetString("Dialog_ConfirmDeleteCache_Message_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes, Close Without Saving.
        /// </summary>
        public static string Dialog_ConfirmDiscard_Button_Yes {
            get {
                return ResourceManager.GetString("Dialog_ConfirmDiscard_Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changes will be lost!.
        /// </summary>
        public static string Dialog_ConfirmDiscard_Message_Line1 {
            get {
                return ResourceManager.GetString("Dialog_ConfirmDiscard_Message_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto-save will be deleted..
        /// </summary>
        public static string Dialog_ConfirmDiscard_Message_Line2 {
            get {
                return ResourceManager.GetString("Dialog_ConfirmDiscard_Message_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure?.
        /// </summary>
        public static string Dialog_ConfirmDiscard_Message_Line3 {
            get {
                return ResourceManager.GetString("Dialog_ConfirmDiscard_Message_Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation.
        /// </summary>
        public static string Dialog_ConfirmDiscard_Title {
            get {
                return ResourceManager.GetString("Dialog_ConfirmDiscard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto-save:.
        /// </summary>
        public static string Dialog_Recovery_AutoSaveVersion {
            get {
                return ResourceManager.GetString("Dialog_Recovery_AutoSaveVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto-save.
        /// </summary>
        public static string Dialog_Recovery_Button_OpenCache {
            get {
                return ResourceManager.GetString("Dialog_Recovery_Button_OpenCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saved.
        /// </summary>
        public static string Dialog_Recovery_Button_OpenSaved {
            get {
                return ResourceManager.GetString("Dialog_Recovery_Button_OpenSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saved version:.
        /// </summary>
        public static string Dialog_Recovery_SavedVersion {
            get {
                return ResourceManager.GetString("Dialog_Recovery_SavedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unsaved Version Found.
        /// </summary>
        public static string Dialog_Recovery_Title {
            get {
                return ResourceManager.GetString("Dialog_Recovery_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Which version to open?.
        /// </summary>
        public static string Dialog_Recovery_WhichVersion {
            get {
                return ResourceManager.GetString("Dialog_Recovery_WhichVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Don&apos;t Save.
        /// </summary>
        public static string Dialog_UnsavedChanges_Button_DontSave {
            get {
                return ResourceManager.GetString("Dialog_UnsavedChanges_Button_DontSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Dialog_UnsavedChanges_Button_Save {
            get {
                return ResourceManager.GetString("Dialog_UnsavedChanges_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save changes before closing?.
        /// </summary>
        public static string Dialog_UnsavedChanges_Message {
            get {
                return ResourceManager.GetString("Dialog_UnsavedChanges_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unsaved Changes.
        /// </summary>
        public static string Dialog_UnsavedChanges_Title {
            get {
                return ResourceManager.GetString("Dialog_UnsavedChanges_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close Tab.
        /// </summary>
        public static string HotKey_File_CloseTab {
            get {
                return ResourceManager.GetString("HotKey_File_CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Project.
        /// </summary>
        public static string HotKey_File_New {
            get {
                return ResourceManager.GetString("HotKey_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Tab.
        /// </summary>
        public static string HotKey_File_NewTab {
            get {
                return ResourceManager.GetString("HotKey_File_NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Project.
        /// </summary>
        public static string HotKey_File_Open {
            get {
                return ResourceManager.GetString("HotKey_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save Project.
        /// </summary>
        public static string HotKey_File_Save {
            get {
                return ResourceManager.GetString("HotKey_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save Project As.
        /// </summary>
        public static string HotKey_File_SaveAs {
            get {
                return ResourceManager.GetString("HotKey_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string Menu_Close {
            get {
                return ResourceManager.GetString("Menu_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Edit.
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modules.
        /// </summary>
        public static string Menu_Modules {
            get {
                return ResourceManager.GetString("Menu_Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Project.
        /// </summary>
        public static string Menu_NewProject {
            get {
                return ResourceManager.GetString("Menu_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open....
        /// </summary>
        public static string Menu_Open {
            get {
                return ResourceManager.GetString("Menu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Redo.
        /// </summary>
        public static string Menu_Redo {
            get {
                return ResourceManager.GetString("Menu_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save As....
        /// </summary>
        public static string Menu_SaveAs {
            get {
                return ResourceManager.GetString("Menu_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///	.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Tools.
        /// </summary>
        public static string Menu_Tools {
            get {
                return ResourceManager.GetString("Menu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Undo.
        /// </summary>
        public static string Menu_Undo {
            get {
                return ResourceManager.GetString("Menu_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _View.
        /// </summary>
        public static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work Modes.
        /// </summary>
        public static string Menu_WorkModes {
            get {
                return ResourceManager.GetString("Menu_WorkModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string MessageBox_Cancel {
            get {
                return ResourceManager.GetString("MessageBox_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compare Versions.
        /// </summary>
        public static string MessageBox_Compare {
            get {
                return ResourceManager.GetString("MessageBox_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not load the project file. The file may be corrupted.
        /// </summary>
        public static string MessageBox_Error_ProjectLoadFailed_Message {
            get {
                return ResourceManager.GetString("MessageBox_Error_ProjectLoadFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to Load Project.
        /// </summary>
        public static string MessageBox_Error_ProjectLoadFailed_Title {
            get {
                return ResourceManager.GetString("MessageBox_Error_ProjectLoadFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The project file may have been moved or deleted.
        /// </summary>
        public static string MessageBox_Error_ProjectNotFound_Message {
            get {
                return ResourceManager.GetString("MessageBox_Error_ProjectNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project Not Found.
        /// </summary>
        public static string MessageBox_Error_ProjectNotFound_Title {
            get {
                return ResourceManager.GetString("MessageBox_Error_ProjectNotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string MessageBox_No {
            get {
                return ResourceManager.GetString("MessageBox_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string MessageBox_OK {
            get {
                return ResourceManager.GetString("MessageBox_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Saved.
        /// </summary>
        public static string MessageBox_OpenSaved {
            get {
                return ResourceManager.GetString("MessageBox_OpenSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Autosave:.
        /// </summary>
        public static string MessageBox_Recovery_CacheDate {
            get {
                return ResourceManager.GetString("MessageBox_Recovery_CacheDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An unsaved version of the project was found..
        /// </summary>
        public static string MessageBox_Recovery_Message {
            get {
                return ResourceManager.GetString("MessageBox_Recovery_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last saved:.
        /// </summary>
        public static string MessageBox_Recovery_SaveDate {
            get {
                return ResourceManager.GetString("MessageBox_Recovery_SaveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Autosave Found.
        /// </summary>
        public static string MessageBox_Recovery_Title {
            get {
                return ResourceManager.GetString("MessageBox_Recovery_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restore.
        /// </summary>
        public static string MessageBox_Restore {
            get {
                return ResourceManager.GetString("MessageBox_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string MessageBox_Yes {
            get {
                return ResourceManager.GetString("MessageBox_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Characters.
        /// </summary>
        public static string Module_Characters {
            get {
                return ResourceManager.GetString("Module_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notes.
        /// </summary>
        public static string Module_Notes {
            get {
                return ResourceManager.GetString("Module_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Statistics.
        /// </summary>
        public static string Module_Statistics {
            get {
                return ResourceManager.GetString("Module_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Synonyms.
        /// </summary>
        public static string Module_Synonyms {
            get {
                return ResourceManager.GetString("Module_Synonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timeline.
        /// </summary>
        public static string Module_Timeline {
            get {
                return ResourceManager.GetString("Module_Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Writer.
        /// </summary>
        public static string Module_Writer {
            get {
                return ResourceManager.GetString("Module_Writer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto-saved.
        /// </summary>
        public static string Notification_AutoSaved {
            get {
                return ResourceManager.GetString("Notification_AutoSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto-saving....
        /// </summary>
        public static string Notification_AutoSaving {
            get {
                return ResourceManager.GetString("Notification_AutoSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Notification_Error {
            get {
                return ResourceManager.GetString("Notification_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Module closed.
        /// </summary>
        public static string Notification_ModuleClosed {
            get {
                return ResourceManager.GetString("Notification_ModuleClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Module opened.
        /// </summary>
        public static string Notification_ModuleOpened {
            get {
                return ResourceManager.GetString("Notification_ModuleOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project closed.
        /// </summary>
        public static string Notification_ProjectClosed {
            get {
                return ResourceManager.GetString("Notification_ProjectClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project opened.
        /// </summary>
        public static string Notification_ProjectOpened {
            get {
                return ResourceManager.GetString("Notification_ProjectOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project saved.
        /// </summary>
        public static string Notification_ProjectSaved {
            get {
                return ResourceManager.GetString("Notification_ProjectSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to save project.
        /// </summary>
        public static string Notification_SavingError {
            get {
                return ResourceManager.GetString("Notification_SavingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WorkMode switched.
        /// </summary>
        public static string Notification_WorkModeSwitched {
            get {
                return ResourceManager.GetString("Notification_WorkModeSwitched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🎮 Game Design Document.
        /// </summary>
        public static string ProjectType_GameDesign {
            get {
                return ResourceManager.GetString("ProjectType_GameDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📖 Novel / Book.
        /// </summary>
        public static string ProjectType_Novel {
            get {
                return ResourceManager.GetString("ProjectType_Novel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ✍️ Poetry Collection.
        /// </summary>
        public static string ProjectType_Poetry {
            get {
                return ResourceManager.GetString("ProjectType_Poetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🎬 Screenplay.
        /// </summary>
        public static string ProjectType_Screenplay {
            get {
                return ResourceManager.GetString("ProjectType_Screenplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language:.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme:.
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lines:.
        /// </summary>
        public static string Status_Lines {
            get {
                return ResourceManager.GetString("Status_Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Words:.
        /// </summary>
        public static string Status_Words {
            get {
                return ResourceManager.GetString("Status_Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browse for Project....
        /// </summary>
        public static string Welcome_BrowseButton {
            get {
                return ResourceManager.GetString("Welcome_BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Project.
        /// </summary>
        public static string Welcome_CreateButton {
            get {
                return ResourceManager.GetString("Welcome_CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📝 New Project.
        /// </summary>
        public static string Welcome_NewProject {
            get {
                return ResourceManager.GetString("Welcome_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📂 Open Project.
        /// </summary>
        public static string Welcome_OpenProject {
            get {
                return ResourceManager.GetString("Welcome_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recent Projects:.
        /// </summary>
        public static string Welcome_RecentProjects {
            get {
                return ResourceManager.GetString("Welcome_RecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose how to start.
        /// </summary>
        public static string Welcome_Subtitle {
            get {
                return ResourceManager.GetString("Welcome_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Writersword.
        /// </summary>
        public static string Welcome_Title {
            get {
                return ResourceManager.GetString("Welcome_Title", resourceCulture);
            }
        }
    }
}
