//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Writersword.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Writersword.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unsaved version found (auto-save).
        /// </summary>
        public static string AutoSave_Banner_CacheFound {
            get {
                return ResourceManager.GetString("AutoSave_Banner_CacheFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Viewing: Auto-save.
        /// </summary>
        public static string AutoSave_Banner_ViewingCache {
            get {
                return ResourceManager.GetString("AutoSave_Banner_ViewingCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Viewing: Saved version.
        /// </summary>
        public static string AutoSave_Banner_ViewingSaved {
            get {
                return ResourceManager.GetString("AutoSave_Banner_ViewingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete Auto-save.
        /// </summary>
        public static string AutoSave_Button_DeleteAutoSave {
            get {
                return ResourceManager.GetString("AutoSave_Button_DeleteAutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Discard Changes.
        /// </summary>
        public static string AutoSave_Button_DiscardChanges {
            get {
                return ResourceManager.GetString("AutoSave_Button_DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Auto-save.
        /// </summary>
        public static string AutoSave_Button_OpenAutoSave {
            get {
                return ResourceManager.GetString("AutoSave_Button_OpenAutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save and Continue.
        /// </summary>
        public static string AutoSave_Button_SaveAndContinue {
            get {
                return ResourceManager.GetString("AutoSave_Button_SaveAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switch to Auto-save.
        /// </summary>
        public static string AutoSave_Button_SwitchToCache {
            get {
                return ResourceManager.GetString("AutoSave_Button_SwitchToCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switch to Saved version.
        /// </summary>
        public static string AutoSave_Button_SwitchToSaved {
            get {
                return ResourceManager.GetString("AutoSave_Button_SwitchToSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto-save:.
        /// </summary>
        public static string AutoSave_Time_AutoSave {
            get {
                return ResourceManager.GetString("AutoSave_Time_AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saved:.
        /// </summary>
        public static string AutoSave_Time_Saved {
            get {
                return ResourceManager.GetString("AutoSave_Time_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        public static string Common_Apply {
            get {
                return ResourceManager.GetString("Common_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete auto-save?.
        /// </summary>
        public static string Dialog_ConfirmDeleteCache_Message_Line1 {
            get {
                return ResourceManager.GetString("Dialog_ConfirmDeleteCache_Message_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changes will be lost..
        /// </summary>
        public static string Dialog_ConfirmDeleteCache_Message_Line2 {
            get {
                return ResourceManager.GetString("Dialog_ConfirmDeleteCache_Message_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes, Close Without Saving.
        /// </summary>
        public static string Dialog_ConfirmDiscard_Button_Yes {
            get {
                return ResourceManager.GetString("Dialog_ConfirmDiscard_Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changes will be lost!.
        /// </summary>
        public static string Dialog_ConfirmDiscard_Message_Line1 {
            get {
                return ResourceManager.GetString("Dialog_ConfirmDiscard_Message_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto-save will be deleted..
        /// </summary>
        public static string Dialog_ConfirmDiscard_Message_Line2 {
            get {
                return ResourceManager.GetString("Dialog_ConfirmDiscard_Message_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure?.
        /// </summary>
        public static string Dialog_ConfirmDiscard_Message_Line3 {
            get {
                return ResourceManager.GetString("Dialog_ConfirmDiscard_Message_Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation.
        /// </summary>
        public static string Dialog_ConfirmDiscard_Title {
            get {
                return ResourceManager.GetString("Dialog_ConfirmDiscard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto-save:.
        /// </summary>
        public static string Dialog_Recovery_AutoSaveVersion {
            get {
                return ResourceManager.GetString("Dialog_Recovery_AutoSaveVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto-save.
        /// </summary>
        public static string Dialog_Recovery_Button_OpenCache {
            get {
                return ResourceManager.GetString("Dialog_Recovery_Button_OpenCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saved.
        /// </summary>
        public static string Dialog_Recovery_Button_OpenSaved {
            get {
                return ResourceManager.GetString("Dialog_Recovery_Button_OpenSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saved version:.
        /// </summary>
        public static string Dialog_Recovery_SavedVersion {
            get {
                return ResourceManager.GetString("Dialog_Recovery_SavedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unsaved Version Found.
        /// </summary>
        public static string Dialog_Recovery_Title {
            get {
                return ResourceManager.GetString("Dialog_Recovery_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Which version to open?.
        /// </summary>
        public static string Dialog_Recovery_WhichVersion {
            get {
                return ResourceManager.GetString("Dialog_Recovery_WhichVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your local configuration will be lost. This action cannot be undone. Continue?.
        /// </summary>
        public static string Dialog_ResetToDefaultMessage {
            get {
                return ResourceManager.GetString("Dialog_ResetToDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset to Default Configuration?.
        /// </summary>
        public static string Dialog_ResetToDefaultTitle {
            get {
                return ResourceManager.GetString("Dialog_ResetToDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your local configuration will be replaced with the global one. Continue?.
        /// </summary>
        public static string Dialog_ResetToGlobalMessage {
            get {
                return ResourceManager.GetString("Dialog_ResetToGlobalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset to Global Configuration?.
        /// </summary>
        public static string Dialog_ResetToGlobalTitle {
            get {
                return ResourceManager.GetString("Dialog_ResetToGlobalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Don&apos;t Save.
        /// </summary>
        public static string Dialog_UnsavedChanges_Button_DontSave {
            get {
                return ResourceManager.GetString("Dialog_UnsavedChanges_Button_DontSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Dialog_UnsavedChanges_Button_Save {
            get {
                return ResourceManager.GetString("Dialog_UnsavedChanges_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Document.
        /// </summary>
        public static string Dialog_UnsavedChanges_Document {
            get {
                return ResourceManager.GetString("Dialog_UnsavedChanges_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на contains unsaved changes..
        /// </summary>
        public static string Dialog_UnsavedChanges_HasUnsaved {
            get {
                return ResourceManager.GetString("Dialog_UnsavedChanges_HasUnsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save changes before closing?.
        /// </summary>
        public static string Dialog_UnsavedChanges_Message {
            get {
                return ResourceManager.GetString("Dialog_UnsavedChanges_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unsaved Changes.
        /// </summary>
        public static string Dialog_UnsavedChanges_Title {
            get {
                return ResourceManager.GetString("Dialog_UnsavedChanges_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add binding.
        /// </summary>
        public static string HotKey_AddBinding {
            get {
                return ResourceManager.GetString("HotKey_AddBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string HotKey_Cancel {
            get {
                return ResourceManager.GetString("HotKey_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string HotKey_Category_Edit {
            get {
                return ResourceManager.GetString("HotKey_Category_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        public static string HotKey_Category_File {
            get {
                return ResourceManager.GetString("HotKey_Category_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Formatting.
        /// </summary>
        public static string HotKey_Category_Formatting {
            get {
                return ResourceManager.GetString("HotKey_Category_Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        public static string HotKey_Category_Help {
            get {
                return ResourceManager.GetString("HotKey_Category_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Navigation.
        /// </summary>
        public static string HotKey_Category_Navigation {
            get {
                return ResourceManager.GetString("HotKey_Category_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tools.
        /// </summary>
        public static string HotKey_Category_Tools {
            get {
                return ResourceManager.GetString("HotKey_Category_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View.
        /// </summary>
        public static string HotKey_Category_View {
            get {
                return ResourceManager.GetString("HotKey_Category_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Action.
        /// </summary>
        public static string HotKey_Col_Action {
            get {
                return ResourceManager.GetString("HotKey_Col_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current.
        /// </summary>
        public static string HotKey_Col_Current {
            get {
                return ResourceManager.GetString("HotKey_Col_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        public static string HotKey_Col_Default {
            get {
                return ResourceManager.GetString("HotKey_Col_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prefix.
        /// </summary>
        public static string HotKey_Col_Prefix {
            get {
                return ResourceManager.GetString("HotKey_Col_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scope.
        /// </summary>
        public static string HotKey_Col_Scope {
            get {
                return ResourceManager.GetString("HotKey_Col_Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Critical conflict.
        /// </summary>
        public static string HotKey_Conflict_Critical {
            get {
                return ResourceManager.GetString("HotKey_Conflict_Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        public static string HotKey_Conflict_Warning {
            get {
                return ResourceManager.GetString("HotKey_Conflict_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string HotKey_Edit {
            get {
                return ResourceManager.GetString("HotKey_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Redo.
        /// </summary>
        public static string HotKey_Edit_Redo {
            get {
                return ResourceManager.GetString("HotKey_Edit_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Undo.
        /// </summary>
        public static string HotKey_Edit_Undo {
            get {
                return ResourceManager.GetString("HotKey_Edit_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete — clear binding.
        /// </summary>
        public static string HotKey_EditHint_Delete {
            get {
                return ResourceManager.GetString("HotKey_EditHint_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Escape — cancel editing.
        /// </summary>
        public static string HotKey_EditHint_Escape {
            get {
                return ResourceManager.GetString("HotKey_EditHint_Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This combination is reserved as a prefix.
        /// </summary>
        public static string HotKey_Error_BlockedByPrefix {
            get {
                return ResourceManager.GetString("HotKey_Error_BlockedByPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This combination conflicts with another hotkey.
        /// </summary>
        public static string HotKey_Error_Conflict {
            get {
                return ResourceManager.GetString("HotKey_Error_Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close All Tabs.
        /// </summary>
        public static string HotKey_File_CloseAllTabs {
            get {
                return ResourceManager.GetString("HotKey_File_CloseAllTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close Other Tabs.
        /// </summary>
        public static string HotKey_File_CloseOtherTabs {
            get {
                return ResourceManager.GetString("HotKey_File_CloseOtherTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close Tab.
        /// </summary>
        public static string HotKey_File_CloseTab {
            get {
                return ResourceManager.GetString("HotKey_File_CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string HotKey_File_Exit {
            get {
                return ResourceManager.GetString("HotKey_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Project.
        /// </summary>
        public static string HotKey_File_New {
            get {
                return ResourceManager.GetString("HotKey_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Tab.
        /// </summary>
        public static string HotKey_File_NewTab {
            get {
                return ResourceManager.GetString("HotKey_File_NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Project.
        /// </summary>
        public static string HotKey_File_Open {
            get {
                return ResourceManager.GetString("HotKey_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save Project.
        /// </summary>
        public static string HotKey_File_Save {
            get {
                return ResourceManager.GetString("HotKey_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save All.
        /// </summary>
        public static string HotKey_File_SaveAll {
            get {
                return ResourceManager.GetString("HotKey_File_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save Project As.
        /// </summary>
        public static string HotKey_File_SaveAs {
            get {
                return ResourceManager.GetString("HotKey_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string HotKey_File_Settings {
            get {
                return ResourceManager.GetString("HotKey_File_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search commands....
        /// </summary>
        public static string HotKey_Filter_Watermark {
            get {
                return ResourceManager.GetString("HotKey_Filter_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reserved as prefix.
        /// </summary>
        public static string HotKey_IsPrefix {
            get {
                return ResourceManager.GetString("HotKey_IsPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Critical conflict — always intercepts.
        /// </summary>
        public static string HotKey_Legend_Critical {
            get {
                return ResourceManager.GetString("HotKey_Legend_Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning — conflict between focused modules.
        /// </summary>
        public static string HotKey_Legend_Warning {
            get {
                return ResourceManager.GetString("HotKey_Legend_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Module is not running.
        /// </summary>
        public static string HotKey_ModuleInactive {
            get {
                return ResourceManager.GetString("HotKey_ModuleInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not assigned.
        /// </summary>
        public static string HotKey_NotAssigned {
            get {
                return ResourceManager.GetString("HotKey_NotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add prefix.
        /// </summary>
        public static string HotKey_Prefix_Add {
            get {
                return ResourceManager.GetString("HotKey_Prefix_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto.
        /// </summary>
        public static string HotKey_Prefix_AutoDerived {
            get {
                return ResourceManager.GetString("HotKey_Prefix_AutoDerived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comment.
        /// </summary>
        public static string HotKey_Prefix_Col_Comment {
            get {
                return ResourceManager.GetString("HotKey_Prefix_Col_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gesture.
        /// </summary>
        public static string HotKey_Prefix_Col_Gesture {
            get {
                return ResourceManager.GetString("HotKey_Prefix_Col_Gesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Used by.
        /// </summary>
        public static string HotKey_Prefix_Col_UsedBy {
            get {
                return ResourceManager.GetString("HotKey_Prefix_Col_UsedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comment (optional).
        /// </summary>
        public static string HotKey_Prefix_CommentPlaceholder {
            get {
                return ResourceManager.GetString("HotKey_Prefix_CommentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This prefix is already registered.
        /// </summary>
        public static string HotKey_Prefix_Error_AlreadyExists {
            get {
                return ResourceManager.GetString("HotKey_Prefix_Error_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This gesture is already used as a hotkey.
        /// </summary>
        public static string HotKey_Prefix_Error_BlockedByHotKey {
            get {
                return ResourceManager.GetString("HotKey_Prefix_Error_BlockedByHotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot remove — hotkeys use this prefix.
        /// </summary>
        public static string HotKey_Prefix_Error_InUse {
            get {
                return ResourceManager.GetString("HotKey_Prefix_Error_InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click to pick prefix for sequence.
        /// </summary>
        public static string HotKey_Prefix_PickTooltip {
            get {
                return ResourceManager.GetString("HotKey_Prefix_PickTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press key combination....
        /// </summary>
        public static string HotKey_Prefix_PressKey {
            get {
                return ResourceManager.GetString("HotKey_Prefix_PressKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string HotKey_Prefix_Remove {
            get {
                return ResourceManager.GetString("HotKey_Prefix_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not used.
        /// </summary>
        public static string HotKey_Prefix_UsedByNone {
            get {
                return ResourceManager.GetString("HotKey_Prefix_UsedByNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press a key....
        /// </summary>
        public static string HotKey_PressKey {
            get {
                return ResourceManager.GetString("HotKey_PressKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove binding.
        /// </summary>
        public static string HotKey_RemoveBinding {
            get {
                return ResourceManager.GetString("HotKey_RemoveBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset to default.
        /// </summary>
        public static string HotKey_Reset {
            get {
                return ResourceManager.GetString("HotKey_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset all.
        /// </summary>
        public static string HotKey_ResetAll {
            get {
                return ResourceManager.GetString("HotKey_ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Global.
        /// </summary>
        public static string HotKey_Section_Global {
            get {
                return ResourceManager.GetString("HotKey_Section_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bindings.
        /// </summary>
        public static string HotKey_Tab_Bindings {
            get {
                return ResourceManager.GetString("HotKey_Tab_Bindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prefixes.
        /// </summary>
        public static string HotKey_Tab_Prefixes {
            get {
                return ResourceManager.GetString("HotKey_Tab_Prefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fullscreen.
        /// </summary>
        public static string HotKey_View_Fullscreen {
            get {
                return ResourceManager.GetString("HotKey_View_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy.
        /// </summary>
        public static string Menu_Edit_Copy {
            get {
                return ResourceManager.GetString("Menu_Edit_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cut.
        /// </summary>
        public static string Menu_Edit_Cut {
            get {
                return ResourceManager.GetString("Menu_Edit_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find.
        /// </summary>
        public static string Menu_Edit_Find {
            get {
                return ResourceManager.GetString("Menu_Edit_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find and Replace.
        /// </summary>
        public static string Menu_Edit_FindReplace {
            get {
                return ResourceManager.GetString("Menu_Edit_FindReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paste.
        /// </summary>
        public static string Menu_Edit_Paste {
            get {
                return ResourceManager.GetString("Menu_Edit_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Redo.
        /// </summary>
        public static string Menu_Edit_Redo {
            get {
                return ResourceManager.GetString("Menu_Edit_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select All.
        /// </summary>
        public static string Menu_Edit_SelectAll {
            get {
                return ResourceManager.GetString("Menu_Edit_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Undo.
        /// </summary>
        public static string Menu_Edit_Undo {
            get {
                return ResourceManager.GetString("Menu_Edit_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close All Tabs.
        /// </summary>
        public static string Menu_File_CloseAllTabs {
            get {
                return ResourceManager.GetString("Menu_File_CloseAllTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close Other Tabs.
        /// </summary>
        public static string Menu_File_CloseOtherTabs {
            get {
                return ResourceManager.GetString("Menu_File_CloseOtherTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string Menu_File_CloseTab {
            get {
                return ResourceManager.GetString("Menu_File_CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Project.
        /// </summary>
        public static string Menu_File_NewProject {
            get {
                return ResourceManager.GetString("Menu_File_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open....
        /// </summary>
        public static string Menu_File_OpenProject {
            get {
                return ResourceManager.GetString("Menu_File_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recent Projects.
        /// </summary>
        public static string Menu_File_RecentProjects {
            get {
                return ResourceManager.GetString("Menu_File_RecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Menu_File_Save {
            get {
                return ResourceManager.GetString("Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save All.
        /// </summary>
        public static string Menu_File_SaveAll {
            get {
                return ResourceManager.GetString("Menu_File_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save As....
        /// </summary>
        public static string Menu_File_SaveAs {
            get {
                return ResourceManager.GetString("Menu_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Menu_File_Settings {
            get {
                return ResourceManager.GetString("Menu_File_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check for Updates.
        /// </summary>
        public static string Menu_Help_CheckUpdates {
            get {
                return ResourceManager.GetString("Menu_Help_CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Documentation.
        /// </summary>
        public static string Menu_Help_Documentation {
            get {
                return ResourceManager.GetString("Menu_Help_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tools.
        /// </summary>
        public static string Menu_Tools {
            get {
                return ResourceManager.GetString("Menu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Statistics.
        /// </summary>
        public static string Menu_Tools_Statistics {
            get {
                return ResourceManager.GetString("Menu_Tools_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View.
        /// </summary>
        public static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fullscreen.
        /// </summary>
        public static string Menu_View_Fullscreen {
            get {
                return ResourceManager.GetString("Menu_View_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modules.
        /// </summary>
        public static string Menu_View_Modules {
            get {
                return ResourceManager.GetString("Menu_View_Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work Modes.
        /// </summary>
        public static string Menu_View_WorkModes {
            get {
                return ResourceManager.GetString("Menu_View_WorkModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Workspace.
        /// </summary>
        public static string Menu_Workspace {
            get {
                return ResourceManager.GetString("Menu_Workspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset to Default.
        /// </summary>
        public static string Menu_Workspace_ResetToDefault {
            get {
                return ResourceManager.GetString("Menu_Workspace_ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset to Global Settings.
        /// </summary>
        public static string Menu_Workspace_ResetToGlobal {
            get {
                return ResourceManager.GetString("Menu_Workspace_ResetToGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save Configuration.
        /// </summary>
        public static string Menu_Workspace_SaveConfiguration {
            get {
                return ResourceManager.GetString("Menu_Workspace_SaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save for This Project.
        /// </summary>
        public static string Menu_Workspace_SaveForProject {
            get {
                return ResourceManager.GetString("Menu_Workspace_SaveForProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as Global Settings for Project Type.
        /// </summary>
        public static string Menu_Workspace_SaveForType {
            get {
                return ResourceManager.GetString("Menu_Workspace_SaveForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string MessageBox_Cancel {
            get {
                return ResourceManager.GetString("MessageBox_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compare Versions.
        /// </summary>
        public static string MessageBox_Compare {
            get {
                return ResourceManager.GetString("MessageBox_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not load the project file. The file may be corrupted.
        /// </summary>
        public static string MessageBox_Error_ProjectLoadFailed_Message {
            get {
                return ResourceManager.GetString("MessageBox_Error_ProjectLoadFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to Load Project.
        /// </summary>
        public static string MessageBox_Error_ProjectLoadFailed_Title {
            get {
                return ResourceManager.GetString("MessageBox_Error_ProjectLoadFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The project file may have been moved or deleted.
        /// </summary>
        public static string MessageBox_Error_ProjectNotFound_Message {
            get {
                return ResourceManager.GetString("MessageBox_Error_ProjectNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project Not Found.
        /// </summary>
        public static string MessageBox_Error_ProjectNotFound_Title {
            get {
                return ResourceManager.GetString("MessageBox_Error_ProjectNotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string MessageBox_No {
            get {
                return ResourceManager.GetString("MessageBox_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string MessageBox_OK {
            get {
                return ResourceManager.GetString("MessageBox_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Saved.
        /// </summary>
        public static string MessageBox_OpenSaved {
            get {
                return ResourceManager.GetString("MessageBox_OpenSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Autosave:.
        /// </summary>
        public static string MessageBox_Recovery_CacheDate {
            get {
                return ResourceManager.GetString("MessageBox_Recovery_CacheDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An unsaved version of the project was found..
        /// </summary>
        public static string MessageBox_Recovery_Message {
            get {
                return ResourceManager.GetString("MessageBox_Recovery_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last saved:.
        /// </summary>
        public static string MessageBox_Recovery_SaveDate {
            get {
                return ResourceManager.GetString("MessageBox_Recovery_SaveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Autosave Found.
        /// </summary>
        public static string MessageBox_Recovery_Title {
            get {
                return ResourceManager.GetString("MessageBox_Recovery_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restore.
        /// </summary>
        public static string MessageBox_Restore {
            get {
                return ResourceManager.GetString("MessageBox_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string MessageBox_Yes {
            get {
                return ResourceManager.GetString("MessageBox_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Characters.
        /// </summary>
        public static string Module_Characters {
            get {
                return ResourceManager.GetString("Module_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notes.
        /// </summary>
        public static string Module_Notes {
            get {
                return ResourceManager.GetString("Module_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Statistics.
        /// </summary>
        public static string Module_Statistics {
            get {
                return ResourceManager.GetString("Module_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Synonyms.
        /// </summary>
        public static string Module_Synonyms {
            get {
                return ResourceManager.GetString("Module_Synonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timeline.
        /// </summary>
        public static string Module_Timeline {
            get {
                return ResourceManager.GetString("Module_Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Writer.
        /// </summary>
        public static string Module_Writer {
            get {
                return ResourceManager.GetString("Module_Writer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto-saved.
        /// </summary>
        public static string Notification_AutoSaved {
            get {
                return ResourceManager.GetString("Notification_AutoSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto-saving....
        /// </summary>
        public static string Notification_AutoSaving {
            get {
                return ResourceManager.GetString("Notification_AutoSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Notification_Error {
            get {
                return ResourceManager.GetString("Notification_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Module closed.
        /// </summary>
        public static string Notification_ModuleClosed {
            get {
                return ResourceManager.GetString("Notification_ModuleClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Module opened.
        /// </summary>
        public static string Notification_ModuleOpened {
            get {
                return ResourceManager.GetString("Notification_ModuleOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project closed.
        /// </summary>
        public static string Notification_ProjectClosed {
            get {
                return ResourceManager.GetString("Notification_ProjectClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project opened.
        /// </summary>
        public static string Notification_ProjectOpened {
            get {
                return ResourceManager.GetString("Notification_ProjectOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project saved.
        /// </summary>
        public static string Notification_ProjectSaved {
            get {
                return ResourceManager.GetString("Notification_ProjectSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to save project.
        /// </summary>
        public static string Notification_SavingError {
            get {
                return ResourceManager.GetString("Notification_SavingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WorkMode switched.
        /// </summary>
        public static string Notification_WorkModeSwitched {
            get {
                return ResourceManager.GetString("Notification_WorkModeSwitched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configuration reset to default.
        /// </summary>
        public static string Notification_WorkspaceResetDefault {
            get {
                return ResourceManager.GetString("Notification_WorkspaceResetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configuration reset to global.
        /// </summary>
        public static string Notification_WorkspaceResetGlobal {
            get {
                return ResourceManager.GetString("Notification_WorkspaceResetGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configuration saved globally.
        /// </summary>
        public static string Notification_WorkspaceSavedGlobal {
            get {
                return ResourceManager.GetString("Notification_WorkspaceSavedGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configuration saved for project.
        /// </summary>
        public static string Notification_WorkspaceSavedProject {
            get {
                return ResourceManager.GetString("Notification_WorkspaceSavedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modules.
        /// </summary>
        public static string Panel_Modules_Title {
            get {
                return ResourceManager.GetString("Panel_Modules_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string Print_Close {
            get {
                return ResourceManager.GetString("Print_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First page.
        /// </summary>
        public static string Print_FirstPage {
            get {
                return ResourceManager.GetString("Print_FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last page.
        /// </summary>
        public static string Print_LastPage {
            get {
                return ResourceManager.GetString("Print_LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next page.
        /// </summary>
        public static string Print_NextPage {
            get {
                return ResourceManager.GetString("Print_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на of.
        /// </summary>
        public static string Print_PageOf {
            get {
                return ResourceManager.GetString("Print_PageOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page.
        /// </summary>
        public static string Print_PagePrefix {
            get {
                return ResourceManager.GetString("Print_PagePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous page.
        /// </summary>
        public static string Print_PrevPage {
            get {
                return ResourceManager.GetString("Print_PrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Print.
        /// </summary>
        public static string Print_PrintBtn {
            get {
                return ResourceManager.GetString("Print_PrintBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rendering....
        /// </summary>
        public static string Print_Rendering {
            get {
                return ResourceManager.GetString("Print_Rendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as PDF.
        /// </summary>
        public static string Print_SavePdf {
            get {
                return ResourceManager.GetString("Print_SavePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zoom in.
        /// </summary>
        public static string Print_ZoomIn {
            get {
                return ResourceManager.GetString("Print_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zoom out.
        /// </summary>
        public static string Print_ZoomOut {
            get {
                return ResourceManager.GetString("Print_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset zoom.
        /// </summary>
        public static string Print_ZoomReset {
            get {
                return ResourceManager.GetString("Print_ZoomReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🎮 Game Design Document.
        /// </summary>
        public static string ProjectType_GameDesign {
            get {
                return ResourceManager.GetString("ProjectType_GameDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📖 Novel / Book.
        /// </summary>
        public static string ProjectType_Novel {
            get {
                return ResourceManager.GetString("ProjectType_Novel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ✍️ Poetry Collection.
        /// </summary>
        public static string ProjectType_Poetry {
            get {
                return ResourceManager.GetString("ProjectType_Poetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🎬 Screenplay.
        /// </summary>
        public static string ProjectType_Screenplay {
            get {
                return ResourceManager.GetString("ProjectType_Screenplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⚠️ VIEWING: AUTO-SAVE.
        /// </summary>
        public static string Recovery_Banner_ViewingCache {
            get {
                return ResourceManager.GetString("Recovery_Banner_ViewingCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ✅ VIEWING: SAVED VERSION.
        /// </summary>
        public static string Recovery_Banner_ViewingSaved {
            get {
                return ResourceManager.GetString("Recovery_Banner_ViewingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete Cache.
        /// </summary>
        public static string Recovery_Button_DeleteCache {
            get {
                return ResourceManager.GetString("Recovery_Button_DeleteCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Recovery_Button_Save {
            get {
                return ResourceManager.GetString("Recovery_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Switch Version.
        /// </summary>
        public static string Recovery_Button_Switch {
            get {
                return ResourceManager.GetString("Recovery_Button_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changes apply to all projects globally and override project-level settings.
        /// </summary>
        public static string Settings_Banner_Global {
            get {
                return ResourceManager.GetString("Settings_Banner_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changes apply to this project only and are saved inside the project file.
        /// </summary>
        public static string Settings_Banner_Project {
            get {
                return ResourceManager.GetString("Settings_Banner_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current global settings will be applied to this project..
        /// </summary>
        public static string Settings_Confirm_ApplyToProject_Message {
            get {
                return ResourceManager.GetString("Settings_Confirm_ApplyToProject_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply to project?.
        /// </summary>
        public static string Settings_Confirm_ApplyToProject_Title {
            get {
                return ResourceManager.GetString("Settings_Confirm_ApplyToProject_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на These settings will become the default for all future projects..
        /// </summary>
        public static string Settings_Confirm_PromoteToGlobal_Message {
            get {
                return ResourceManager.GetString("Settings_Confirm_PromoteToGlobal_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as global?.
        /// </summary>
        public static string Settings_Confirm_PromoteToGlobal_Title {
            get {
                return ResourceManager.GetString("Settings_Confirm_PromoteToGlobal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All settings will be reset to their default values. This cannot be undone..
        /// </summary>
        public static string Settings_Confirm_ResetAllToDefaults_Message {
            get {
                return ResourceManager.GetString("Settings_Confirm_ResetAllToDefaults_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset to defaults?.
        /// </summary>
        public static string Settings_Confirm_ResetAllToDefaults_Title {
            get {
                return ResourceManager.GetString("Settings_Confirm_ResetAllToDefaults_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All local settings will be reset to global values. This cannot be undone..
        /// </summary>
        public static string Settings_Confirm_ResetAllToGlobal_Message {
            get {
                return ResourceManager.GetString("Settings_Confirm_ResetAllToGlobal_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset to global?.
        /// </summary>
        public static string Settings_Confirm_ResetAllToGlobal_Title {
            get {
                return ResourceManager.GetString("Settings_Confirm_ResetAllToGlobal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current settings will be applied to all future projects of this type..
        /// </summary>
        public static string Settings_Confirm_SaveAsGlobal_Message {
            get {
                return ResourceManager.GetString("Settings_Confirm_SaveAsGlobal_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as global?.
        /// </summary>
        public static string Settings_Confirm_SaveAsGlobal_Title {
            get {
                return ResourceManager.GetString("Settings_Confirm_SaveAsGlobal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset to default.
        /// </summary>
        public static string Settings_Field_ResetToDefault {
            get {
                return ResourceManager.GetString("Settings_Field_ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset to global.
        /// </summary>
        public static string Settings_Field_ResetToGlobal {
            get {
                return ResourceManager.GetString("Settings_Field_ResetToGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string Settings_General_Language {
            get {
                return ResourceManager.GetString("Settings_General_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart now.
        /// </summary>
        public static string Settings_General_RestartNow {
            get {
                return ResourceManager.GetString("Settings_General_RestartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart required to apply language changes.
        /// </summary>
        public static string Settings_General_RestartRequired {
            get {
                return ResourceManager.GetString("Settings_General_RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme.
        /// </summary>
        public static string Settings_General_Theme {
            get {
                return ResourceManager.GetString("Settings_General_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark.
        /// </summary>
        public static string Settings_General_Theme_Dark {
            get {
                return ResourceManager.GetString("Settings_General_Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light.
        /// </summary>
        public static string Settings_General_Theme_Light {
            get {
                return ResourceManager.GetString("Settings_General_Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sepia.
        /// </summary>
        public static string Settings_General_Theme_Sepia {
            get {
                return ResourceManager.GetString("Settings_General_Theme_Sepia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language:.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No project is open.
        /// </summary>
        public static string Settings_NoProjectOpen {
            get {
                return ResourceManager.GetString("Settings_NoProjectOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GLOBAL MODULE SETTINGS.
        /// </summary>
        public static string Settings_Section_GlobalModuleSettings {
            get {
                return ResourceManager.GetString("Settings_Section_GlobalModuleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на THIS PROJECT SETTINGS.
        /// </summary>
        public static string Settings_Section_ThisProjectSettings {
            get {
                return ResourceManager.GetString("Settings_Section_ThisProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        public static string Settings_Tab_General {
            get {
                return ResourceManager.GetString("Settings_Tab_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keybindings.
        /// </summary>
        public static string Settings_Tab_Keybindings {
            get {
                return ResourceManager.GetString("Settings_Tab_Keybindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project.
        /// </summary>
        public static string Settings_Tab_Project {
            get {
                return ResourceManager.GetString("Settings_Tab_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme:.
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply to this project.
        /// </summary>
        public static string Settings_Toolbar_ApplyToProject {
            get {
                return ResourceManager.GetString("Settings_Toolbar_ApplyToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as global.
        /// </summary>
        public static string Settings_Toolbar_PromoteToGlobal {
            get {
                return ResourceManager.GetString("Settings_Toolbar_PromoteToGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset all to defaults.
        /// </summary>
        public static string Settings_Toolbar_ResetAllToDefaults {
            get {
                return ResourceManager.GetString("Settings_Toolbar_ResetAllToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset all to defaults.
        /// </summary>
        public static string Settings_Toolbar_ResetAllToDefaultsLocal {
            get {
                return ResourceManager.GetString("Settings_Toolbar_ResetAllToDefaultsLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset all to global.
        /// </summary>
        public static string Settings_Toolbar_ResetAllToGlobal {
            get {
                return ResourceManager.GetString("Settings_Toolbar_ResetAllToGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as global.
        /// </summary>
        public static string Settings_Toolbar_SaveAsGlobal {
            get {
                return ResourceManager.GetString("Settings_Toolbar_SaveAsGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lines:.
        /// </summary>
        public static string Status_Lines {
            get {
                return ResourceManager.GetString("Status_Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Words:.
        /// </summary>
        public static string Status_Words {
            get {
                return ResourceManager.GetString("Status_Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browse for Project....
        /// </summary>
        public static string Welcome_BrowseButton {
            get {
                return ResourceManager.GetString("Welcome_BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Project.
        /// </summary>
        public static string Welcome_CreateButton {
            get {
                return ResourceManager.GetString("Welcome_CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📝 New Project.
        /// </summary>
        public static string Welcome_NewProject {
            get {
                return ResourceManager.GetString("Welcome_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📂 Open Project.
        /// </summary>
        public static string Welcome_OpenProject {
            get {
                return ResourceManager.GetString("Welcome_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recent Projects:.
        /// </summary>
        public static string Welcome_RecentProjects {
            get {
                return ResourceManager.GetString("Welcome_RecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose how to start.
        /// </summary>
        public static string Welcome_Subtitle {
            get {
                return ResourceManager.GetString("Welcome_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Writersword.
        /// </summary>
        public static string Welcome_Title {
            get {
                return ResourceManager.GetString("Welcome_Title", resourceCulture);
            }
        }
    }
}
