// <auto-generated>
//   DO NOT EDIT — regenerate via ResGen or Visual Studio.
// </auto-generated>
#nullable enable
namespace Writersword.Modules.TextEditor.Resources
{
    using System.Resources;
    using System.Globalization;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextEditorStrings
    {
        private static ResourceManager? _rm;
        private static CultureInfo? _culture;

        internal TextEditorStrings() { }

        public static ResourceManager ResourceManager
        {
            get
            {
                if (_rm is null)
                    _rm = new ResourceManager(
                        "Writersword.Src.Modules.TextEditor.Resources.TextEditorStrings",
                        typeof(TextEditorStrings).Assembly);
                return _rm;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static CultureInfo? Culture { get => _culture; set => _culture = value; }

        public static string Align_Center => ResourceManager.GetString("Align_Center", _culture)!;
        public static string Align_Justify => ResourceManager.GetString("Align_Justify", _culture)!;
        public static string Align_Left => ResourceManager.GetString("Align_Left", _culture)!;
        public static string Align_Right => ResourceManager.GetString("Align_Right", _culture)!;
        public static string Break_SectionContinuous => ResourceManager.GetString("Break_SectionContinuous", _culture)!;
        public static string Break_SectionNextPage => ResourceManager.GetString("Break_SectionNextPage", _culture)!;
        public static string Case_Lower => ResourceManager.GetString("Case_Lower", _culture)!;
        public static string Case_Sentence => ResourceManager.GetString("Case_Sentence", _culture)!;
        public static string Case_Title => ResourceManager.GetString("Case_Title", _culture)!;
        public static string Case_Toggle => ResourceManager.GetString("Case_Toggle", _culture)!;
        public static string Case_Upper => ResourceManager.GetString("Case_Upper", _culture)!;
        public static string Clipboard_Group => ResourceManager.GetString("Clipboard_Group", _culture)!;
        public static string Columns_One => ResourceManager.GetString("Columns_One", _culture)!;
        public static string Columns_Three => ResourceManager.GetString("Columns_Three", _culture)!;
        public static string Columns_Two => ResourceManager.GetString("Columns_Two", _culture)!;
        public static string Description => ResourceManager.GetString("Description", _culture)!;
        public static string DisplayName => ResourceManager.GetString("DisplayName", _culture)!;
        public static string Edit_Group => ResourceManager.GetString("Edit_Group", _culture)!;
        public static string Edit_Redo => ResourceManager.GetString("Edit_Redo", _culture)!;
        public static string Edit_SelectAll => ResourceManager.GetString("Edit_SelectAll", _culture)!;
        public static string Edit_Undo => ResourceManager.GetString("Edit_Undo", _culture)!;
        public static string Editor_ReadOnly => ResourceManager.GetString("Editor_ReadOnly", _culture)!;
        public static string Export_Docx => ResourceManager.GetString("Export_Docx", _culture)!;
        public static string Export_Markdown => ResourceManager.GetString("Export_Markdown", _culture)!;
        public static string Export_PDF => ResourceManager.GetString("Export_PDF", _culture)!;
        public static string Export_Txt => ResourceManager.GetString("Export_Txt", _culture)!;
        public static string Find_Title => ResourceManager.GetString("Find_Title", _culture)!;
        public static string FindReplace_Title => ResourceManager.GetString("FindReplace_Title", _culture)!;
        public static string Font_Group => ResourceManager.GetString("Font_Group", _culture)!;
        public static string Format_AllCaps => ResourceManager.GetString("Format_AllCaps", _culture)!;
        public static string Format_Bold => ResourceManager.GetString("Format_Bold", _culture)!;
        public static string Format_Bold_Letter => ResourceManager.GetString("Format_Bold_Letter", _culture)!;
        public static string Format_ChangeCase => ResourceManager.GetString("Format_ChangeCase", _culture)!;
        public static string Format_ClearFormatting => ResourceManager.GetString("Format_ClearFormatting", _culture)!;
        public static string Format_Copy => ResourceManager.GetString("Format_Copy", _culture)!;
        public static string Format_Cut => ResourceManager.GetString("Format_Cut", _culture)!;
        public static string Format_DecreaseFontSize => ResourceManager.GetString("Format_DecreaseFontSize", _culture)!;
        public static string Format_FontFamily => ResourceManager.GetString("Format_FontFamily", _culture)!;
        public static string Format_FontSize => ResourceManager.GetString("Format_FontSize", _culture)!;
        public static string Format_Highlight => ResourceManager.GetString("Format_Highlight", _culture)!;
        public static string Format_IncreaseFontSize => ResourceManager.GetString("Format_IncreaseFontSize", _culture)!;
        public static string Format_Italic => ResourceManager.GetString("Format_Italic", _culture)!;
        public static string Format_Italic_Letter => ResourceManager.GetString("Format_Italic_Letter", _culture)!;
        public static string Format_Paste => ResourceManager.GetString("Format_Paste", _culture)!;
        public static string Format_Strikethrough => ResourceManager.GetString("Format_Strikethrough", _culture)!;
        public static string Format_Strikethrough_Letter => ResourceManager.GetString("Format_Strikethrough_Letter", _culture)!;
        public static string Format_Subscript => ResourceManager.GetString("Format_Subscript", _culture)!;
        public static string Format_Superscript => ResourceManager.GetString("Format_Superscript", _culture)!;
        public static string Format_TextColor => ResourceManager.GetString("Format_TextColor", _culture)!;
        public static string Format_Underline => ResourceManager.GetString("Format_Underline", _culture)!;
        public static string Format_Underline_Letter => ResourceManager.GetString("Format_Underline_Letter", _culture)!;
        public static string Insert_Bookmark => ResourceManager.GetString("Insert_Bookmark", _culture)!;
        public static string Insert_Comment => ResourceManager.GetString("Insert_Comment", _culture)!;
        public static string Insert_Footnote => ResourceManager.GetString("Insert_Footnote", _culture)!;
        public static string Insert_Hyperlink => ResourceManager.GetString("Insert_Hyperlink", _culture)!;
        public static string Insert_Image => ResourceManager.GetString("Insert_Image", _culture)!;
        public static string Insert_Links_Group => ResourceManager.GetString("Insert_Links_Group", _culture)!;
        public static string Insert_Media_Group => ResourceManager.GetString("Insert_Media_Group", _culture)!;
        public static string Insert_Page_Group => ResourceManager.GetString("Insert_Page_Group", _culture)!;
        public static string Insert_PageBreak => ResourceManager.GetString("Insert_PageBreak", _culture)!;
        public static string Insert_Shape => ResourceManager.GetString("Insert_Shape", _culture)!;
        public static string Insert_Table => ResourceManager.GetString("Insert_Table", _culture)!;
        public static string Insert_Table_Group => ResourceManager.GetString("Insert_Table_Group", _culture)!;
        public static string Insert_TextBox => ResourceManager.GetString("Insert_TextBox", _culture)!;
        public static string Insert_TOC => ResourceManager.GetString("Insert_TOC", _culture)!;
        public static string Layout_Breaks_Group => ResourceManager.GetString("Layout_Breaks_Group", _culture)!;
        public static string Layout_Columns => ResourceManager.GetString("Layout_Columns", _culture)!;
        public static string Layout_Margins => ResourceManager.GetString("Layout_Margins", _culture)!;
        public static string Layout_Orientation => ResourceManager.GetString("Layout_Orientation", _culture)!;
        public static string Layout_Page_Group => ResourceManager.GetString("Layout_Page_Group", _culture)!;
        public static string Layout_PageSize => ResourceManager.GetString("Layout_PageSize", _culture)!;
        public static string Layout_SectionBreak => ResourceManager.GetString("Layout_SectionBreak", _culture)!;
        public static string List_Bullet => ResourceManager.GetString("List_Bullet", _culture)!;
        public static string List_Multilevel => ResourceManager.GetString("List_Multilevel", _culture)!;
        public static string List_Numbered => ResourceManager.GetString("List_Numbered", _culture)!;
        public static string Orientation_Landscape => ResourceManager.GetString("Orientation_Landscape", _culture)!;
        public static string Orientation_Portrait => ResourceManager.GetString("Orientation_Portrait", _culture)!;
        public static string Para_Indent => ResourceManager.GetString("Para_Indent", _culture)!;
        public static string Para_LineSpacing => ResourceManager.GetString("Para_LineSpacing", _culture)!;
        public static string Para_Outdent => ResourceManager.GetString("Para_Outdent", _culture)!;
        public static string Para_SpaceAfter => ResourceManager.GetString("Para_SpaceAfter", _culture)!;
        public static string Para_SpaceBefore => ResourceManager.GetString("Para_SpaceBefore", _culture)!;
        public static string Paragraph_Group => ResourceManager.GetString("Paragraph_Group", _culture)!;
        public static string Print_Title => ResourceManager.GetString("Print_Title", _culture)!;
        public static string Ref_Endnote => ResourceManager.GetString("Ref_Endnote", _culture)!;
        public static string Ref_Export_Group => ResourceManager.GetString("Ref_Export_Group", _culture)!;
        public static string Ref_Footnotes_Group => ResourceManager.GetString("Ref_Footnotes_Group", _culture)!;
        public static string Ref_TOC_Group => ResourceManager.GetString("Ref_TOC_Group", _culture)!;
        public static string Ref_Tools_Group => ResourceManager.GetString("Ref_Tools_Group", _culture)!;
        public static string Ref_UpdateTOC => ResourceManager.GetString("Ref_UpdateTOC", _culture)!;
        public static string Ribbon_Home => ResourceManager.GetString("Ribbon_Home", _culture)!;
        public static string Ribbon_Insert => ResourceManager.GetString("Ribbon_Insert", _culture)!;
        public static string Ribbon_Layout => ResourceManager.GetString("Ribbon_Layout", _culture)!;
        public static string Ribbon_References => ResourceManager.GetString("Ribbon_References", _culture)!;
        public static string Ribbon_Styles => ResourceManager.GetString("Ribbon_Styles", _culture)!;
        public static string Ribbon_Table => ResourceManager.GetString("Ribbon_Table", _culture)!;
        public static string Settings_AutoReplaceEnabled => ResourceManager.GetString("Settings_AutoReplaceEnabled", _culture)!;
        public static string Settings_AutoReplaceGroup => ResourceManager.GetString("Settings_AutoReplaceGroup", _culture)!;
        public static string Settings_AutoSaveGroup => ResourceManager.GetString("Settings_AutoSaveGroup", _culture)!;
        public static string Settings_AutoSaveHint => ResourceManager.GetString("Settings_AutoSaveHint", _culture)!;
        public static string Settings_AutoSaveInterval => ResourceManager.GetString("Settings_AutoSaveInterval", _culture)!;
        public static string Settings_AutoSaveSeconds => ResourceManager.GetString("Settings_AutoSaveSeconds", _culture)!;
        public static string Settings_DefaultLanguage => ResourceManager.GetString("Settings_DefaultLanguage", _culture)!;
        public static string Settings_DefaultViewMode => ResourceManager.GetString("Settings_DefaultViewMode", _culture)!;
        public static string Settings_DefaultZoom => ResourceManager.GetString("Settings_DefaultZoom", _culture)!;
        public static string Settings_FontFamily => ResourceManager.GetString("Settings_FontFamily", _culture)!;
        public static string Settings_FontGroup => ResourceManager.GetString("Settings_FontGroup", _culture)!;
        public static string Settings_FontSize => ResourceManager.GetString("Settings_FontSize", _culture)!;
        public static string Settings_MonitorGroup => ResourceManager.GetString("Settings_MonitorGroup", _culture)!;
        public static string Settings_MonitorSize => ResourceManager.GetString("Settings_MonitorSize", _culture)!;
        public static string Settings_MonitorSizeHint => ResourceManager.GetString("Settings_MonitorSizeHint", _culture)!;
        public static string Settings_MonitorSizeUnit => ResourceManager.GetString("Settings_MonitorSizeUnit", _culture)!;
        public static string Settings_Preview => ResourceManager.GetString("Settings_Preview", _culture)!;
        public static string Settings_PreviewText => ResourceManager.GetString("Settings_PreviewText", _culture)!;
        public static string Settings_ResetToDefaults => ResourceManager.GetString("Settings_ResetToDefaults", _culture)!;
        public static string Settings_ShowFormattingMarks => ResourceManager.GetString("Settings_ShowFormattingMarks", _culture)!;
        public static string Settings_ShowRuler => ResourceManager.GetString("Settings_ShowRuler", _culture)!;
        public static string Settings_ShowSpellErrors => ResourceManager.GetString("Settings_ShowSpellErrors", _culture)!;
        public static string Settings_SpellCheckEnabled => ResourceManager.GetString("Settings_SpellCheckEnabled", _culture)!;
        public static string Settings_SpellGroup => ResourceManager.GetString("Settings_SpellGroup", _culture)!;
        public static string Settings_ViewGroup => ResourceManager.GetString("Settings_ViewGroup", _culture)!;
        public static string Shape_Arrow => ResourceManager.GetString("Shape_Arrow", _culture)!;
        public static string Shape_Callout => ResourceManager.GetString("Shape_Callout", _culture)!;
        public static string Shape_Ellipse => ResourceManager.GetString("Shape_Ellipse", _culture)!;
        public static string Shape_Line => ResourceManager.GetString("Shape_Line", _culture)!;
        public static string Shape_Rectangle => ResourceManager.GetString("Shape_Rectangle", _culture)!;
        public static string SpellCheck_Active => ResourceManager.GetString("SpellCheck_Active", _culture)!;
        public static string SpellCheck_Title => ResourceManager.GetString("SpellCheck_Title", _culture)!;
        public static string Status_Chars => ResourceManager.GetString("Status_Chars", _culture)!;
        public static string Status_FitToPhysicalSize => ResourceManager.GetString("Status_FitToPhysicalSize", _culture)!;
        public static string Status_Page => ResourceManager.GetString("Status_Page", _culture)!;
        public static string Status_Pages => ResourceManager.GetString("Status_Pages", _culture)!;
        public static string Status_Paragraphs => ResourceManager.GetString("Status_Paragraphs", _culture)!;
        public static string Status_Words => ResourceManager.GetString("Status_Words", _culture)!;
        public static string Style_Code => ResourceManager.GetString("Style_Code", _culture)!;
        public static string Style_Heading1 => ResourceManager.GetString("Style_Heading1", _culture)!;
        public static string Style_Heading2 => ResourceManager.GetString("Style_Heading2", _culture)!;
        public static string Style_Heading3 => ResourceManager.GetString("Style_Heading3", _culture)!;
        public static string Style_Heading4 => ResourceManager.GetString("Style_Heading4", _culture)!;
        public static string Style_Heading5 => ResourceManager.GetString("Style_Heading5", _culture)!;
        public static string Style_Heading6 => ResourceManager.GetString("Style_Heading6", _culture)!;
        public static string Style_Normal => ResourceManager.GetString("Style_Normal", _culture)!;
        public static string Style_NoSpacing => ResourceManager.GetString("Style_NoSpacing", _culture)!;
        public static string Style_Quote => ResourceManager.GetString("Style_Quote", _culture)!;
        public static string Styles_EditStyles => ResourceManager.GetString("Styles_EditStyles", _culture)!;
        public static string Styles_ResetToDefaults => ResourceManager.GetString("Styles_ResetToDefaults", _culture)!;
        public static string Styles_SaveFromCursor => ResourceManager.GetString("Styles_SaveFromCursor", _culture)!;
        public static string Table_AddColumnLeft => ResourceManager.GetString("Table_AddColumnLeft", _culture)!;
        public static string Table_AddColumnRight => ResourceManager.GetString("Table_AddColumnRight", _culture)!;
        public static string Table_AddRowAbove => ResourceManager.GetString("Table_AddRowAbove", _culture)!;
        public static string Table_AddRowBelow => ResourceManager.GetString("Table_AddRowBelow", _culture)!;
        public static string Table_Align_Group => ResourceManager.GetString("Table_Align_Group", _culture)!;
        public static string Table_AlignBottomCenter => ResourceManager.GetString("Table_AlignBottomCenter", _culture)!;
        public static string Table_AlignBottomLeft => ResourceManager.GetString("Table_AlignBottomLeft", _culture)!;
        public static string Table_AlignBottomRight => ResourceManager.GetString("Table_AlignBottomRight", _culture)!;
        public static string Table_AlignMiddleCenter => ResourceManager.GetString("Table_AlignMiddleCenter", _culture)!;
        public static string Table_AlignMiddleLeft => ResourceManager.GetString("Table_AlignMiddleLeft", _culture)!;
        public static string Table_AlignMiddleRight => ResourceManager.GetString("Table_AlignMiddleRight", _culture)!;
        public static string Table_AlignTopCenter => ResourceManager.GetString("Table_AlignTopCenter", _culture)!;
        public static string Table_AlignTopLeft => ResourceManager.GetString("Table_AlignTopLeft", _culture)!;
        public static string Table_AlignTopRight => ResourceManager.GetString("Table_AlignTopRight", _culture)!;
        public static string Table_AutoFit => ResourceManager.GetString("Table_AutoFit", _culture)!;
        public static string Table_BorderAll => ResourceManager.GetString("Table_BorderAll", _culture)!;
        public static string Table_BorderBottom => ResourceManager.GetString("Table_BorderBottom", _culture)!;
        public static string Table_BorderInner => ResourceManager.GetString("Table_BorderInner", _culture)!;
        public static string Table_BorderLeft => ResourceManager.GetString("Table_BorderLeft", _culture)!;
        public static string Table_BorderNone => ResourceManager.GetString("Table_BorderNone", _culture)!;
        public static string Table_BorderOuter => ResourceManager.GetString("Table_BorderOuter", _culture)!;
        public static string Table_BorderRight => ResourceManager.GetString("Table_BorderRight", _culture)!;
        public static string Table_Borders => ResourceManager.GetString("Table_Borders", _culture)!;
        public static string Table_BorderTop => ResourceManager.GetString("Table_BorderTop", _culture)!;
        public static string Table_CellColor => ResourceManager.GetString("Table_CellColor", _culture)!;
        public static string Table_Cells_Group => ResourceManager.GetString("Table_Cells_Group", _culture)!;
        public static string Table_ColorBlue => ResourceManager.GetString("Table_ColorBlue", _culture)!;
        public static string Table_ColorGray => ResourceManager.GetString("Table_ColorGray", _culture)!;
        public static string Table_ColorGreen => ResourceManager.GetString("Table_ColorGreen", _culture)!;
        public static string Table_ColorNone => ResourceManager.GetString("Table_ColorNone", _culture)!;
        public static string Table_ColorRed => ResourceManager.GetString("Table_ColorRed", _culture)!;
        public static string Table_ColorYellow => ResourceManager.GetString("Table_ColorYellow", _culture)!;
        public static string Table_Columns_Group => ResourceManager.GetString("Table_Columns_Group", _culture)!;
        public static string Table_Delete => ResourceManager.GetString("Table_Delete", _culture)!;
        public static string Table_DeleteColumn => ResourceManager.GetString("Table_DeleteColumn", _culture)!;
        public static string Table_DeleteRow => ResourceManager.GetString("Table_DeleteRow", _culture)!;
        public static string Table_DistributeColumns => ResourceManager.GetString("Table_DistributeColumns", _culture)!;
        public static string Table_DistributeRows => ResourceManager.GetString("Table_DistributeRows", _culture)!;
        public static string Table_Group => ResourceManager.GetString("Table_Group", _culture)!;
        public static string Table_Header_Group => ResourceManager.GetString("Table_Header_Group", _culture)!;
        public static string Table_MergeCells => ResourceManager.GetString("Table_MergeCells", _culture)!;
        public static string Table_RepeatHeader => ResourceManager.GetString("Table_RepeatHeader", _culture)!;
        public static string Table_Rows_Group => ResourceManager.GetString("Table_Rows_Group", _culture)!;
        public static string Table_Sort_Group => ResourceManager.GetString("Table_Sort_Group", _culture)!;
        public static string Table_SortAsc => ResourceManager.GetString("Table_SortAsc", _culture)!;
        public static string Table_SortDesc => ResourceManager.GetString("Table_SortDesc", _culture)!;
        public static string Table_SplitCell => ResourceManager.GetString("Table_SplitCell", _culture)!;
        public static string Table_Split_Group => ResourceManager.GetString("Table_Split_Group", _culture)!;
        public static string Table_SplitByRow => ResourceManager.GetString("Table_SplitByRow", _culture)!;
        public static string Table_SplitByCell => ResourceManager.GetString("Table_SplitByCell", _culture)!;
        public static string Table_BreakLabel => ResourceManager.GetString("Table_BreakLabel", _culture)!;
        public static string Table_ContinuationLabel => ResourceManager.GetString("Table_ContinuationLabel", _culture)!;
        public static string Table_Style_Group => ResourceManager.GetString("Table_Style_Group", _culture)!;
        public static string TextEffect_Glow => ResourceManager.GetString("TextEffect_Glow", _culture)!;
        public static string TextEffect_Outline => ResourceManager.GetString("TextEffect_Outline", _culture)!;
        public static string TextEffect_Reflection => ResourceManager.GetString("TextEffect_Reflection", _culture)!;
        public static string TextEffect_Shadow => ResourceManager.GetString("TextEffect_Shadow", _culture)!;
        public static string TextEffect_Title => ResourceManager.GetString("TextEffect_Title", _culture)!;
        public static string View_CanvasColor => ResourceManager.GetString("View_CanvasColor", _culture)!;
        public static string View_DraftMode => ResourceManager.GetString("View_DraftMode", _culture)!;
        public static string View_FocusMode => ResourceManager.GetString("View_FocusMode", _culture)!;
        public static string View_Fullscreen => ResourceManager.GetString("View_Fullscreen", _culture)!;
        public static string View_PageMode => ResourceManager.GetString("View_PageMode", _culture)!;
        public static string View_ReadingMode => ResourceManager.GetString("View_ReadingMode", _culture)!;
        public static string View_WebMode => ResourceManager.GetString("View_WebMode", _culture)!;
        public static string View_Zoom => ResourceManager.GetString("View_Zoom", _culture)!;
    }
}