//------------------------------------------------------------------------------
// <auto-generated>
//     Строго типизированный доступ к ресурсам SharedStrings.
//     Поддерживается вручную (генератор resx не подключён к проекту).
// </auto-generated>
//------------------------------------------------------------------------------

namespace Writersword.Styles.UserControls
{
    using System;

    public class SharedStrings
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal SharedStrings() { }

        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    var temp = new global::System.Resources.ResourceManager(
                        "Writersword.Styles.UserControls.SharedStrings",
                        typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        // Culture не выставляем — null означает использование CultureInfo.CurrentUICulture,
        // которую LocalizationService задаёт под язык приложения.
        public static global::System.Globalization.CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string ColorPicker_ChangeColor =>
            ResourceManager.GetString("ColorPicker_ChangeColor", resourceCulture)!;

        public static string ColorPicker_BasicColors =>
            ResourceManager.GetString("ColorPicker_BasicColors", resourceCulture)!;

        public static string ColorPicker_ProjectColors =>
            ResourceManager.GetString("ColorPicker_ProjectColors", resourceCulture)!;

        public static string ColorPicker_SaveCurrent =>
            ResourceManager.GetString("ColorPicker_SaveCurrent", resourceCulture)!;

        public static string ColorPicker_SaveTooltip =>
            ResourceManager.GetString("ColorPicker_SaveTooltip", resourceCulture)!;

        public static string ColorPicker_Recent =>
            ResourceManager.GetString("ColorPicker_Recent", resourceCulture)!;

        public static string ColorPicker_RemoveFromPalette =>
            ResourceManager.GetString("ColorPicker_RemoveFromPalette", resourceCulture)!;

        public static string ColorPicker_Configure =>
            ResourceManager.GetString("ColorPicker_Configure", resourceCulture)!;

        public static string ColorEditor_Title =>
            ResourceManager.GetString("ColorEditor_Title", resourceCulture)!;

        public static string ColorEditor_Eyedropper =>
            ResourceManager.GetString("ColorEditor_Eyedropper", resourceCulture)!;

        public static string ColorEditor_Preview =>
            ResourceManager.GetString("ColorEditor_Preview", resourceCulture)!;

        public static string ColorEditor_TabSpectrum =>
            ResourceManager.GetString("ColorEditor_TabSpectrum", resourceCulture)!;

        public static string ColorEditor_TabHoneycomb =>
            ResourceManager.GetString("ColorEditor_TabHoneycomb", resourceCulture)!;

        public static string ColorEditor_MyColors =>
            ResourceManager.GetString("ColorEditor_MyColors", resourceCulture)!;

        public static string ColorEditor_AddCurrent =>
            ResourceManager.GetString("ColorEditor_AddCurrent", resourceCulture)!;

        public static string ColorEditor_EyedropperHint =>
            ResourceManager.GetString("ColorEditor_EyedropperHint", resourceCulture)!;

        public static string ColorEditor_TabWheel =>
            ResourceManager.GetString("ColorEditor_TabWheel", resourceCulture)!;

        public static string ColorEditor_TabValues =>
            ResourceManager.GetString("ColorEditor_TabValues", resourceCulture)!;

        public static string ColorEditor_AvatarRing =>
            ResourceManager.GetString("ColorEditor_AvatarRing", resourceCulture)!;

        public static string ColorEditor_ApplyToAll =>
            ResourceManager.GetString("ColorEditor_ApplyToAll", resourceCulture)!;

        public static string ColorEditor_RingAll =>
            ResourceManager.GetString("ColorEditor_RingAll", resourceCulture)!;

        public static string ColorEditor_RingNone =>
            ResourceManager.GetString("ColorEditor_RingNone", resourceCulture)!;

        public static string ColorEditor_ConfirmAll =>
            ResourceManager.GetString("ColorEditor_ConfirmAll", resourceCulture)!;

        public static string ColorEditor_TabPalettes =>
            ResourceManager.GetString("ColorEditor_TabPalettes", resourceCulture)!;

        public static string Palette_Standard =>
            ResourceManager.GetString("Palette_Standard", resourceCulture)!;

        public static string Palette_Reset =>
            ResourceManager.GetString("Palette_Reset", resourceCulture)!;

        public static string Palette_Palettes =>
            ResourceManager.GetString("Palette_Palettes", resourceCulture)!;

        public static string Palette_New =>
            ResourceManager.GetString("Palette_New", resourceCulture)!;

        public static string Palette_Local =>
            ResourceManager.GetString("Palette_Local", resourceCulture)!;

        public static string Palette_Global =>
            ResourceManager.GetString("Palette_Global", resourceCulture)!;

        public static string Palette_Delete =>
            ResourceManager.GetString("Palette_Delete", resourceCulture)!;

        public static string Palette_ToggleVisible =>
            ResourceManager.GetString("Palette_ToggleVisible", resourceCulture)!;

        public static string Common_Ok =>
            ResourceManager.GetString("Common_Ok", resourceCulture)!;

        public static string Common_Cancel =>
            ResourceManager.GetString("Common_Cancel", resourceCulture)!;
    }
}
