//------------------------------------------------------------------------------
// <auto-generated>
//     Строго типизированный доступ к ресурсам SharedStrings.
//     Поддерживается вручную (генератор resx не подключён к проекту).
// </auto-generated>
//------------------------------------------------------------------------------

namespace Writersword.Styles.UserControls
{
    using System;

    public class SharedStrings
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal SharedStrings() { }

        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    var temp = new global::System.Resources.ResourceManager(
                        "Writersword.Styles.UserControls.SharedStrings",
                        typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        // Culture не выставляем — null означает использование CultureInfo.CurrentUICulture,
        // которую LocalizationService задаёт под язык приложения.
        public static global::System.Globalization.CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string ColorPicker_ChangeColor =>
            ResourceManager.GetString("ColorPicker_ChangeColor", resourceCulture)!;

        public static string ColorPicker_BasicColors =>
            ResourceManager.GetString("ColorPicker_BasicColors", resourceCulture)!;

        public static string ColorPicker_ProjectColors =>
            ResourceManager.GetString("ColorPicker_ProjectColors", resourceCulture)!;

        public static string ColorPicker_SaveCurrent =>
            ResourceManager.GetString("ColorPicker_SaveCurrent", resourceCulture)!;

        public static string ColorPicker_SaveTooltip =>
            ResourceManager.GetString("ColorPicker_SaveTooltip", resourceCulture)!;

        public static string ColorPicker_Recent =>
            ResourceManager.GetString("ColorPicker_Recent", resourceCulture)!;

        public static string ColorPicker_RemoveFromPalette =>
            ResourceManager.GetString("ColorPicker_RemoveFromPalette", resourceCulture)!;

        public static string ColorPicker_Configure =>
            ResourceManager.GetString("ColorPicker_Configure", resourceCulture)!;

        public static string ColorEditor_Title =>
            ResourceManager.GetString("ColorEditor_Title", resourceCulture)!;

        public static string ColorEditor_Eyedropper =>
            ResourceManager.GetString("ColorEditor_Eyedropper", resourceCulture)!;

        public static string ColorEditor_Preview =>
            ResourceManager.GetString("ColorEditor_Preview", resourceCulture)!;

        public static string ColorEditor_TabSpectrum =>
            ResourceManager.GetString("ColorEditor_TabSpectrum", resourceCulture)!;

        public static string ColorEditor_TabHoneycomb =>
            ResourceManager.GetString("ColorEditor_TabHoneycomb", resourceCulture)!;

        public static string ColorEditor_MyColors =>
            ResourceManager.GetString("ColorEditor_MyColors", resourceCulture)!;

        public static string ColorEditor_AddCurrent =>
            ResourceManager.GetString("ColorEditor_AddCurrent", resourceCulture)!;

        public static string ColorEditor_EyedropperHint =>
            ResourceManager.GetString("ColorEditor_EyedropperHint", resourceCulture)!;

        public static string Gradient_Hint_Title =>
            ResourceManager.GetString("Gradient_Hint_Title", resourceCulture)!;

        public static string Gradient_Hint_Body =>
            ResourceManager.GetString("Gradient_Hint_Body", resourceCulture)!;

        public static string ColorEditor_TabWheel =>
            ResourceManager.GetString("ColorEditor_TabWheel", resourceCulture)!;

        public static string ColorEditor_TabValues =>
            ResourceManager.GetString("ColorEditor_TabValues", resourceCulture)!;

        public static string ColorEditor_TabNoise =>
            ResourceManager.GetString("ColorEditor_TabNoise", resourceCulture)!;

        public static string ColorEditor_NoiseRegenerate =>
            ResourceManager.GetString("ColorEditor_NoiseRegenerate", resourceCulture)!;

        public static string ColorEditor_NoiseRegenerateHint =>
            ResourceManager.GetString("ColorEditor_NoiseRegenerateHint", resourceCulture)!;

        public static string ColorEditor_NoiseZoomOut =>
            ResourceManager.GetString("ColorEditor_NoiseZoomOut", resourceCulture)!;

        public static string ColorEditor_NoiseRainbow =>
            ResourceManager.GetString("ColorEditor_NoiseRainbow", resourceCulture)!;

        public static string ColorEditor_NoiseSkin =>
            ResourceManager.GetString("ColorEditor_NoiseSkin", resourceCulture)!;

        public static string ColorEditor_NoisePastel =>
            ResourceManager.GetString("ColorEditor_NoisePastel", resourceCulture)!;

        public static string ColorEditor_NoiseGrayscale =>
            ResourceManager.GetString("ColorEditor_NoiseGrayscale", resourceCulture)!;

        public static string ColorEditor_NoiseNeon =>
            ResourceManager.GetString("ColorEditor_NoiseNeon", resourceCulture)!;

        public static string ColorEditor_NoiseFromPalette =>
            ResourceManager.GetString("ColorEditor_NoiseFromPalette", resourceCulture)!;

        public static string ColorEditor_AvatarRing =>
            ResourceManager.GetString("ColorEditor_AvatarRing", resourceCulture)!;

        public static string ColorEditor_ApplyToAll =>
            ResourceManager.GetString("ColorEditor_ApplyToAll", resourceCulture)!;

        public static string ColorEditor_RingAll =>
            ResourceManager.GetString("ColorEditor_RingAll", resourceCulture)!;

        public static string ColorEditor_RingNone =>
            ResourceManager.GetString("ColorEditor_RingNone", resourceCulture)!;

        public static string ColorEditor_ConfirmAll =>
            ResourceManager.GetString("ColorEditor_ConfirmAll", resourceCulture)!;

        public static string ColorEditor_TabPalettes =>
            ResourceManager.GetString("ColorEditor_TabPalettes", resourceCulture)!;

        public static string Palette_Standard =>
            ResourceManager.GetString("Palette_Standard", resourceCulture)!;

        public static string Palette_Reset =>
            ResourceManager.GetString("Palette_Reset", resourceCulture)!;

        public static string Palette_Palettes =>
            ResourceManager.GetString("Palette_Palettes", resourceCulture)!;

        public static string Palette_New =>
            ResourceManager.GetString("Palette_New", resourceCulture)!;

        public static string Palette_Local =>
            ResourceManager.GetString("Palette_Local", resourceCulture)!;

        public static string Palette_Global =>
            ResourceManager.GetString("Palette_Global", resourceCulture)!;

        public static string Palette_Delete =>
            ResourceManager.GetString("Palette_Delete", resourceCulture)!;

        public static string Palette_ToggleVisible =>
            ResourceManager.GetString("Palette_ToggleVisible", resourceCulture)!;

        public static string Palette_LoadTitle =>
            ResourceManager.GetString("Palette_LoadTitle", resourceCulture)!;

        public static string Palette_TabImport =>
            ResourceManager.GetString("Palette_TabImport", resourceCulture)!;

        public static string Palette_TabExport =>
            ResourceManager.GetString("Palette_TabExport", resourceCulture)!;

        public static string Palette_NamePlaceholder =>
            ResourceManager.GetString("Palette_NamePlaceholder", resourceCulture)!;

        public static string Palette_ImportHint =>
            ResourceManager.GetString("Palette_ImportHint", resourceCulture)!;

        public static string Palette_File =>
            ResourceManager.GetString("Palette_File", resourceCulture)!;

        public static string Palette_Add =>
            ResourceManager.GetString("Palette_Add", resourceCulture)!;

        public static string Palette_ImportEmpty =>
            ResourceManager.GetString("Palette_ImportEmpty", resourceCulture)!;

        public static string Palette_HexList =>
            ResourceManager.GetString("Palette_HexList", resourceCulture)!;

        public static string Palette_SaveFile =>
            ResourceManager.GetString("Palette_SaveFile", resourceCulture)!;

        public static string Palette_Copy =>
            ResourceManager.GetString("Palette_Copy", resourceCulture)!;

        public static string Palette_Close =>
            ResourceManager.GetString("Palette_Close", resourceCulture)!;

        public static string Palette_ScopeHintTitle =>
            ResourceManager.GetString("Palette_ScopeHintTitle", resourceCulture)!;

        public static string Palette_ScopeHintBody =>
            ResourceManager.GetString("Palette_ScopeHintBody", resourceCulture)!;

        public static string Palette_OpenFileTitle =>
            ResourceManager.GetString("Palette_OpenFileTitle", resourceCulture)!;

        public static string Palette_SaveFileTitle =>
            ResourceManager.GetString("Palette_SaveFileTitle", resourceCulture)!;

        public static string Palette_FileTypeLabel =>
            ResourceManager.GetString("Palette_FileTypeLabel", resourceCulture)!;

        public static string Common_Ok =>
            ResourceManager.GetString("Common_Ok", resourceCulture)!;

        public static string Common_Cancel =>
            ResourceManager.GetString("Common_Cancel", resourceCulture)!;
    }
}
