//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Writersword.Modules.Notes.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotesStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotesStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Writersword.Src.Modules.Notes.Resources.NotesStrings", typeof(NotesStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на As text.
        /// </summary>
        public static string Action_CopyPage {
            get {
                return ResourceManager.GetString("Action_CopyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string Action_Dismiss {
            get {
                return ResourceManager.GetString("Action_Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy.
        /// </summary>
        public static string Action_DuplicatePage {
            get {
                return ResourceManager.GetString("Action_DuplicatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New.
        /// </summary>
        public static string Action_NewPage {
            get {
                return ResourceManager.GetString("Action_NewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Down.
        /// </summary>
        public static string Action_PageDown {
            get {
                return ResourceManager.GetString("Action_PageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Up.
        /// </summary>
        public static string Action_PageUp {
            get {
                return ResourceManager.GetString("Action_PageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Action_RemovePage {
            get {
                return ResourceManager.GetString("Action_RemovePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Panel.
        /// </summary>
        public static string Action_TogglePages {
            get {
                return ResourceManager.GetString("Action_TogglePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Undo.
        /// </summary>
        public static string Action_Undo {
            get {
                return ResourceManager.GetString("Action_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bullets.
        /// </summary>
        public static string Block_Bullet {
            get {
                return ResourceManager.GetString("Block_Bullet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task.
        /// </summary>
        public static string Block_Checklist {
            get {
                return ResourceManager.GetString("Block_Checklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code.
        /// </summary>
        public static string Block_Code {
            get {
                return ResourceManager.GetString("Block_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rule.
        /// </summary>
        public static string Block_Divider {
            get {
                return ResourceManager.GetString("Block_Divider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Heading 1.
        /// </summary>
        public static string Block_Heading1 {
            get {
                return ResourceManager.GetString("Block_Heading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Heading 2.
        /// </summary>
        public static string Block_Heading2 {
            get {
                return ResourceManager.GetString("Block_Heading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Heading 3.
        /// </summary>
        public static string Block_Heading3 {
            get {
                return ResourceManager.GetString("Block_Heading3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Numbers.
        /// </summary>
        public static string Block_Numbered {
            get {
                return ResourceManager.GetString("Block_Numbered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Plain.
        /// </summary>
        public static string Block_Paragraph {
            get {
                return ResourceManager.GetString("Block_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quote.
        /// </summary>
        public static string Block_Quote {
            get {
                return ResourceManager.GetString("Block_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quick notes and reminders.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notes.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selection.
        /// </summary>
        public static string Group_Inline {
            get {
                return ResourceManager.GetString("Group_Inline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Line.
        /// </summary>
        public static string Group_Line {
            get {
                return ResourceManager.GetString("Group_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lists.
        /// </summary>
        public static string Group_Lists {
            get {
                return ResourceManager.GetString("Group_Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pages.
        /// </summary>
        public static string Group_Pages {
            get {
                return ResourceManager.GetString("Group_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на # heading · ## subheading · - list · 1. numbering · - [ ] task · &gt; quote · ``` code · --- rule.
        /// </summary>
        public static string Hint_Blocks {
            get {
                return ResourceManager.GetString("Hint_Blocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Just type. Markup is applied as you type:.
        /// </summary>
        public static string Hint_Header {
            get {
                return ResourceManager.GetString("Hint_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на **bold** · *italic* · ~~strike~~ · `code` · ==mark==.
        /// </summary>
        public static string Hint_Inline {
            get {
                return ResourceManager.GetString("Hint_Inline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bold.
        /// </summary>
        public static string Inline_Bold {
            get {
                return ResourceManager.GetString("Inline_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code.
        /// </summary>
        public static string Inline_Code {
            get {
                return ResourceManager.GetString("Inline_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Italic.
        /// </summary>
        public static string Inline_Italic {
            get {
                return ResourceManager.GetString("Inline_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mark.
        /// </summary>
        public static string Inline_Mark {
            get {
                return ResourceManager.GetString("Inline_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Strike.
        /// </summary>
        public static string Inline_Strike {
            get {
                return ResourceManager.GetString("Inline_Strike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Down.
        /// </summary>
        public static string Line_Down {
            get {
                return ResourceManager.GetString("Line_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Highlight.
        /// </summary>
        public static string Line_Highlight {
            get {
                return ResourceManager.GetString("Line_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string Line_Remove {
            get {
                return ResourceManager.GetString("Line_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Strike.
        /// </summary>
        public static string Line_Strike {
            get {
                return ResourceManager.GetString("Line_Strike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Up.
        /// </summary>
        public static string Line_Up {
            get {
                return ResourceManager.GetString("Line_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} — copy.
        /// </summary>
        public static string Page_CopyTitle {
            get {
                return ResourceManager.GetString("Page_CopyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notes.
        /// </summary>
        public static string Page_DefaultTitle {
            get {
                return ResourceManager.GetString("Page_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page {0}.
        /// </summary>
        public static string Page_NewTitle {
            get {
                return ResourceManager.GetString("Page_NewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tasks: {0} of {1}.
        /// </summary>
        public static string Page_Tasks {
            get {
                return ResourceManager.GetString("Page_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page title.
        /// </summary>
        public static string Page_TitleWatermark {
            get {
                return ResourceManager.GetString("Page_TitleWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Untitled page.
        /// </summary>
        public static string Page_Untitled {
            get {
                return ResourceManager.GetString("Page_Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edited {0:dd.MM.yyyy HH:mm}.
        /// </summary>
        public static string Page_UpdatedAt {
            get {
                return ResourceManager.GetString("Page_UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Found {0} of {1}.
        /// </summary>
        public static string Pages_FoundCount {
            get {
                return ResourceManager.GetString("Pages_FoundCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pages.
        /// </summary>
        public static string Pages_Header {
            get {
                return ResourceManager.GetString("Pages_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search pages.
        /// </summary>
        public static string Pages_SearchWatermark {
            get {
                return ResourceManager.GetString("Pages_SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pages: {0}.
        /// </summary>
        public static string Pages_TotalCount {
            get {
                return ResourceManager.GetString("Pages_TotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quick Notes.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Line deleted.
        /// </summary>
        public static string Undo_BlockRemoved {
            get {
                return ResourceManager.GetString("Undo_BlockRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page “{0}” deleted.
        /// </summary>
        public static string Undo_PageRemoved {
            get {
                return ResourceManager.GetString("Undo_PageRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page deletion.
        /// </summary>
        public static string Undo_PageRemovedShort {
            get {
                return ResourceManager.GetString("Undo_PageRemovedShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Styles.
        /// </summary>
        public static string Group_Styles {
            get {
                return ResourceManager.GetString("Group_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на B.
        /// </summary>
        public static string Inline_Bold_Letter {
            get {
                return ResourceManager.GetString("Inline_Bold_Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I.
        /// </summary>
        public static string Inline_Italic_Letter {
            get {
                return ResourceManager.GetString("Inline_Italic_Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на S.
        /// </summary>
        public static string Inline_Strike_Letter {
            get {
                return ResourceManager.GetString("Inline_Strike_Letter", resourceCulture);
            }
        }
        
    }
}
